"""
主要病院・検査センターの初期データを登録する。
実行: python manage.py seed_hospitals
※ すでに同名・同都道府県の施設が存在する場合はスキップする。
"""
from django.core.management.base import BaseCommand
from hospitals.models import Hospital

HOSPITALS = [
    # ── 検査センター ──────────────────────────────
    {
        'name': 'BML 東京ラボラトリー',
        'prefecture': '東京都',
        'address': '東京都練馬区土支田4-20-1',
        'phone': '03-5372-3666',
        'facility_type': 'lab',
        'website': 'https://www.bml.co.jp/',
        'departments': '',
        'inspection_items': '血液,生化学,免疫,微生物,病理,遺伝子',
    },
    {
        'name': 'SRL 新宿ラボラトリー',
        'prefecture': '東京都',
        'address': '東京都渋谷区本町2-44-1',
        'phone': '03-3372-3522',
        'facility_type': 'lab',
        'website': 'https://www.srl.info/',
        'departments': '',
        'inspection_items': '血液,生化学,免疫,微生物,病理,遺伝子,染色体',
    },
    {
        'name': 'LSIメディエンス 東京本社ラボ',
        'prefecture': '東京都',
        'address': '東京都千代田区神田駿河台4-6',
        'phone': '03-3292-3511',
        'facility_type': 'lab',
        'website': 'https://www.lsi-medience.com/',
        'departments': '',
        'inspection_items': '血液,生化学,免疫,微生物,病理,遺伝子',
    },
    {
        'name': 'ファルコバイオシステムズ',
        'prefecture': '大阪府',
        'address': '大阪市淀川区宮原3-4-30',
        'phone': '06-6394-3700',
        'facility_type': 'lab',
        'website': 'https://www.falco.co.jp/',
        'departments': '',
        'inspection_items': '血液,生化学,免疫,微生物,病理',
    },
    {
        'name': '三菱化学メディエンス 名古屋ラボ',
        'prefecture': '愛知県',
        'address': '名古屋市中村区名駅南2-14-19',
        'facility_type': 'lab',
        'website': 'https://www.lsi-medience.com/',
        'departments': '',
        'inspection_items': '血液,生化学,免疫,微生物,病理',
    },
    # ── 大学病院（関東）────────────────────────────
    {
        'name': '東京大学医学部附属病院',
        'prefecture': '東京都',
        'address': '東京都文京区本郷7-3-1',
        'phone': '03-3815-5411',
        'facility_type': 'hospital',
        'beds': 1217,
        'website': 'https://www.h.u-tokyo.ac.jp/',
        'departments': '内科,外科,小児科,産婦人科,精神科,皮膚科,眼科,耳鼻咽喉科,放射線科,麻酔科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子',
    },
    {
        'name': '慶應義塾大学病院',
        'prefecture': '東京都',
        'address': '東京都新宿区信濃町35',
        'phone': '03-3353-1211',
        'facility_type': 'hospital',
        'beds': 960,
        'website': 'https://www.hosp.keio.ac.jp/',
        'departments': '内科,外科,小児科,産婦人科,精神科,皮膚科,眼科,耳鼻咽喉科,放射線科,麻酔科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子',
    },
    {
        'name': '順天堂大学医学部附属順天堂医院',
        'prefecture': '東京都',
        'address': '東京都文京区本郷3-1-3',
        'phone': '03-3813-3111',
        'facility_type': 'hospital',
        'beds': 1046,
        'website': 'https://www.juntendo.ac.jp/hospital/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科,泌尿器科,放射線科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理',
    },
    {
        'name': '日本医科大学付属病院',
        'prefecture': '東京都',
        'address': '東京都文京区千駄木1-1-5',
        'phone': '03-3822-2131',
        'facility_type': 'hospital',
        'beds': 820,
        'website': 'https://www.nms.ac.jp/hospital/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理',
    },
    {
        'name': '東京女子医科大学病院',
        'prefecture': '東京都',
        'address': '東京都新宿区河田町8-1',
        'phone': '03-3353-8111',
        'facility_type': 'hospital',
        'beds': 880,
        'website': 'https://www.twmu.ac.jp/TWMU/',
        'departments': '内科,外科,小児科,産婦人科,腎臓内科,心臓病センター',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子',
    },
    {
        'name': '横浜市立大学附属病院',
        'prefecture': '神奈川県',
        'address': '横浜市金沢区福浦3-9',
        'phone': '045-787-2800',
        'facility_type': 'hospital',
        'beds': 720,
        'website': 'https://www-user.yokohama-cu.ac.jp/~ycu-hp/',
        'departments': '内科,外科,小児科,産婦人科,精神科,整形外科,眼科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理',
    },
    {
        'name': '埼玉医科大学病院',
        'prefecture': '埼玉県',
        'address': '埼玉県入間郡毛呂山町毛呂本郷38',
        'phone': '049-276-1111',
        'facility_type': 'hospital',
        'beds': 760,
        'website': 'https://www.saitama-med.ac.jp/hospital/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理',
    },
    {
        'name': '千葉大学医学部附属病院',
        'prefecture': '千葉県',
        'address': '千葉市中央区亥鼻1-8-1',
        'phone': '043-222-7171',
        'facility_type': 'hospital',
        'beds': 850,
        'website': 'https://www.ho.chiba-u.ac.jp/',
        'departments': '内科,外科,小児科,産婦人科,精神科,整形外科,眼科,耳鼻咽喉科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子',
    },
    # ── 大学病院（関西）────────────────────────────
    {
        'name': '大阪大学医学部附属病院',
        'prefecture': '大阪府',
        'address': '大阪府吹田市山田丘2-15',
        'phone': '06-6879-5111',
        'facility_type': 'hospital',
        'beds': 1074,
        'website': 'https://www.hosp.med.osaka-u.ac.jp/',
        'departments': '内科,外科,小児科,産婦人科,精神科,整形外科,眼科,耳鼻咽喉科,放射線科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子',
    },
    {
        'name': '京都大学医学部附属病院',
        'prefecture': '京都府',
        'address': '京都市左京区聖護院川原町54',
        'phone': '075-751-3111',
        'facility_type': 'hospital',
        'beds': 1121,
        'website': 'https://www.kuhp.kyoto-u.ac.jp/',
        'departments': '内科,外科,小児科,産婦人科,精神科,整形外科,眼科,耳鼻咽喉科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子',
    },
    {
        'name': '近畿大学病院',
        'prefecture': '大阪府',
        'address': '大阪府大阪狭山市大野東377-2',
        'phone': '072-366-0221',
        'facility_type': 'hospital',
        'beds': 1059,
        'website': 'https://www.med.kindai.ac.jp/hospital/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理',
    },
    {
        'name': '神戸大学医学部附属病院',
        'prefecture': '兵庫県',
        'address': '神戸市中央区楠町7-5-2',
        'phone': '078-382-5111',
        'facility_type': 'hospital',
        'beds': 714,
        'website': 'https://www.hosp.kobe-u.ac.jp/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理',
    },
    # ── 大学病院（中部・東北・九州）──────────────────
    {
        'name': '名古屋大学医学部附属病院',
        'prefecture': '愛知県',
        'address': '名古屋市昭和区鶴舞町65',
        'phone': '052-741-2111',
        'facility_type': 'hospital',
        'beds': 1013,
        'website': 'https://www.med.nagoya-u.ac.jp/hospital/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子',
    },
    {
        'name': '東北大学病院',
        'prefecture': '宮城県',
        'address': '仙台市青葉区星陵町1-1',
        'phone': '022-717-7000',
        'facility_type': 'hospital',
        'beds': 1119,
        'website': 'https://www.hosp.tohoku.ac.jp/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子',
    },
    {
        'name': '九州大学病院',
        'prefecture': '福岡県',
        'address': '福岡市東区馬出3-1-1',
        'phone': '092-641-1151',
        'facility_type': 'hospital',
        'beds': 1239,
        'website': 'https://www.hosp.kyushu-u.ac.jp/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子',
    },
    {
        'name': '北海道大学病院',
        'prefecture': '北海道',
        'address': '札幌市北区北14条西5丁目',
        'phone': '011-716-1161',
        'facility_type': 'hospital',
        'beds': 953,
        'website': 'https://www.huhp.hokudai.ac.jp/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理',
    },
    {
        'name': '広島大学病院',
        'prefecture': '広島県',
        'address': '広島市南区霞1-2-3',
        'phone': '082-257-5555',
        'facility_type': 'hospital',
        'beds': 850,
        'website': 'https://www.hosp.hiroshima-u.ac.jp/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理',
    },
    # ── 国立病院機構 ───────────────────────────────
    {
        'name': '国立病院機構 東京医療センター',
        'prefecture': '東京都',
        'address': '東京都目黒区東が丘2-5-1',
        'phone': '03-3411-0111',
        'facility_type': 'hospital',
        'beds': 760,
        'website': 'https://tokyo-iryocenter.hosp.go.jp/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理',
    },
    {
        'name': '国立病院機構 大阪医療センター',
        'prefecture': '大阪府',
        'address': '大阪市中央区法円坂2-1-14',
        'phone': '06-6942-1331',
        'facility_type': 'hospital',
        'beds': 720,
        'website': 'https://osaka.hosp.go.jp/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理',
    },
    {
        'name': '国立病院機構 名古屋医療センター',
        'prefecture': '愛知県',
        'address': '名古屋市中区三の丸4-1-1',
        'phone': '052-951-1111',
        'facility_type': 'hospital',
        'beds': 720,
        'website': 'https://nagoya.hosp.go.jp/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理',
    },
    # ── 日本赤十字社 ───────────────────────────────
    {
        'name': '日本赤十字社医療センター',
        'prefecture': '東京都',
        'address': '東京都渋谷区広尾4-1-22',
        'phone': '03-3400-1311',
        'facility_type': 'hospital',
        'beds': 707,
        'website': 'https://www.med.jrc.or.jp/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科,救急科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理',
    },
    {
        'name': '大阪赤十字病院',
        'prefecture': '大阪府',
        'address': '大阪市天王寺区筆ヶ崎町5-30',
        'phone': '06-6774-5111',
        'facility_type': 'hospital',
        'beds': 874,
        'website': 'https://www.osaka-med.jrc.or.jp/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理',
    },
    {
        'name': '名古屋第一赤十字病院',
        'prefecture': '愛知県',
        'address': '名古屋市中村区道下町3-35',
        'phone': '052-481-5111',
        'facility_type': 'hospital',
        'beds': 726,
        'website': 'https://www.nagoya-1st.jrc.or.jp/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理',
    },
    {
        'name': '仙台赤十字病院',
        'prefecture': '宮城県',
        'address': '仙台市若林区南鍛冶町43',
        'phone': '022-243-1111',
        'facility_type': 'hospital',
        'beds': 320,
        'website': 'https://www.sendai.jrc.or.jp/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理',
    },
    # ── 済生会 ─────────────────────────────────────
    {
        'name': '済生会中央病院',
        'prefecture': '東京都',
        'address': '東京都港区三田1-4-17',
        'phone': '03-3451-8211',
        'facility_type': 'hospital',
        'beds': 535,
        'website': 'https://www.saisei-chuo.jp/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理',
    },
    {
        'name': '大阪府済生会中津病院',
        'prefecture': '大阪府',
        'address': '大阪市北区芝田2-10-39',
        'phone': '06-6372-0333',
        'facility_type': 'hospital',
        'beds': 585,
        'website': 'https://www.osaka-nakatu.saiseikai.or.jp/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理',
    },
    # ── 大学病院（残り全施設）──────────────────────
    {'name': '東北医科薬科大学病院', 'prefecture': '宮城県', 'address': '仙台市宮城野区福室1-12-1', 'phone': '022-784-3065', 'facility_type': 'hospital', 'beds': 320, 'website': 'https://www.tohoku-mpu.ac.jp/hospital/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '防衛医科大学校病院', 'prefecture': '埼玉県', 'address': '所沢市並木3-2', 'phone': '04-2995-1511', 'facility_type': 'hospital', 'beds': 800, 'website': 'https://www.ndmc.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子'},
    {'name': '東京医科歯科大学病院', 'prefecture': '東京都', 'address': '東京都文京区湯島1-5-45', 'phone': '03-3813-6111', 'facility_type': 'hospital', 'beds': 832, 'website': 'https://www.tmd.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科,歯科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子'},
    {'name': '東京医科大学病院', 'prefecture': '東京都', 'address': '東京都新宿区西新宿6-7-1', 'phone': '03-3342-6111', 'facility_type': 'hospital', 'beds': 1015, 'website': 'https://hospinfo.tokyo-med.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '帝京大学医学部附属病院', 'prefecture': '東京都', 'address': '東京都板橋区加賀2-11-1', 'phone': '03-3964-1111', 'facility_type': 'hospital', 'beds': 1058, 'website': 'https://www.teikyo-u.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '杏林大学医学部付属病院', 'prefecture': '東京都', 'address': '東京都三鷹市新川6-20-2', 'phone': '0422-47-5511', 'facility_type': 'hospital', 'beds': 1008, 'website': 'https://www.kyorin-u.ac.jp/hosp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '日本大学医学部附属板橋病院', 'prefecture': '東京都', 'address': '東京都板橋区大谷口上町30-1', 'phone': '03-3972-8111', 'facility_type': 'hospital', 'beds': 912, 'website': 'https://www.med.nihon-u.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '獨協医科大学病院', 'prefecture': '栃木県', 'address': '壬生町北小林880', 'phone': '0282-86-1111', 'facility_type': 'hospital', 'beds': 1155, 'website': 'https://www.dokkyomed.ac.jp/hosp-m/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子'},
    {'name': '富山大学附属病院', 'prefecture': '富山県', 'address': '富山市杉谷2630', 'phone': '076-434-2281', 'facility_type': 'hospital', 'beds': 612, 'website': 'https://www.hosp.u-toyama.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '山梨大学医学部附属病院', 'prefecture': '山梨県', 'address': '中央市下河東1110', 'phone': '055-273-1111', 'facility_type': 'hospital', 'beds': 636, 'website': 'https://www.yamanashi.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '岐阜大学医学部附属病院', 'prefecture': '岐阜県', 'address': '岐阜市柳戸1-1', 'phone': '058-230-6000', 'facility_type': 'hospital', 'beds': 606, 'website': 'https://www.hguh.gifu-u.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子'},
    {'name': '大阪公立大学医学部附属病院', 'prefecture': '大阪府', 'address': '大阪市阿倍野区旭町1-5-7', 'phone': '06-6645-2121', 'facility_type': 'hospital', 'beds': 1065, 'website': 'https://www2.omu.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子'},
    {'name': '京都府立医科大学附属病院', 'prefecture': '京都府', 'address': '京都市上京区河原町通広小路上ル梶井町465', 'phone': '075-251-5111', 'facility_type': 'hospital', 'beds': 1015, 'website': 'https://www.kpu-m.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子'},
    {'name': '久留米大学病院', 'prefecture': '福岡県', 'address': '久留米市旭町67', 'phone': '0942-35-3311', 'facility_type': 'hospital', 'beds': 1068, 'website': 'https://www.kurume-u.ac.jp/site/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '福岡大学病院', 'prefecture': '福岡県', 'address': '福岡市城南区七隈7-45-1', 'phone': '092-801-1011', 'facility_type': 'hospital', 'beds': 910, 'website': 'https://www.hop.fukuoka-u.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    # ── 大学病院（追加）────────────────────────────
    {'name': '札幌医科大学附属病院', 'prefecture': '北海道', 'address': '札幌市中央区南1条西16丁目291', 'phone': '011-611-2111', 'facility_type': 'hospital', 'beds': 700, 'website': 'https://web.sapmed.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '旭川医科大学病院', 'prefecture': '北海道', 'address': '旭川市緑が丘東2条1丁目1-1', 'phone': '0166-65-2111', 'facility_type': 'hospital', 'beds': 620, 'website': 'https://www.asahikawa-med.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '弘前大学医学部附属病院', 'prefecture': '青森県', 'address': '弘前市本町53', 'phone': '0172-33-5111', 'facility_type': 'hospital', 'beds': 664, 'website': 'https://www.med.hirosaki-u.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '岩手医科大学附属病院', 'prefecture': '岩手県', 'address': '矢巾町医大通2-1-1', 'phone': '019-613-7111', 'facility_type': 'hospital', 'beds': 1000, 'website': 'https://www.iwate-med.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子'},
    {'name': '秋田大学医学部附属病院', 'prefecture': '秋田県', 'address': '秋田市広面字蚕養44-2', 'phone': '018-834-1111', 'facility_type': 'hospital', 'beds': 701, 'website': 'https://www.hos.akita-u.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '山形大学医学部附属病院', 'prefecture': '山形県', 'address': '山形市飯田西2-2-2', 'phone': '023-633-1122', 'facility_type': 'hospital', 'beds': 636, 'website': 'https://hospi.med.yamagata-u.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '福島県立医科大学附属病院', 'prefecture': '福島県', 'address': '福島市光が丘1', 'phone': '024-547-1111', 'facility_type': 'hospital', 'beds': 840, 'website': 'https://www.fmu.ac.jp/home/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '筑波大学附属病院', 'prefecture': '茨城県', 'address': 'つくば市天久保2-1-1', 'phone': '029-853-3900', 'facility_type': 'hospital', 'beds': 850, 'website': 'https://www.hosp.tsukuba.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子'},
    {'name': '自治医科大学附属病院', 'prefecture': '栃木県', 'address': '下野市薬師寺3311-1', 'phone': '0285-44-2111', 'facility_type': 'hospital', 'beds': 765, 'website': 'https://www.jichi.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '群馬大学医学部附属病院', 'prefecture': '群馬県', 'address': '前橋市昭和町3-39-15', 'phone': '027-220-7111', 'facility_type': 'hospital', 'beds': 720, 'website': 'https://hospital.med.gunma-u.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '東京慈恵会医科大学附属病院', 'prefecture': '東京都', 'address': '東京都港区西新橋3-25-8', 'phone': '03-3433-1111', 'facility_type': 'hospital', 'beds': 950, 'website': 'https://www.jikei.ac.jp/hospital/honin/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子'},
    {'name': '昭和大学病院', 'prefecture': '東京都', 'address': '東京都品川区旗の台1-5-8', 'phone': '03-3784-8000', 'facility_type': 'hospital', 'beds': 760, 'website': 'https://www.showa-u.ac.jp/SUH/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '東邦大学医療センター大森病院', 'prefecture': '東京都', 'address': '東京都大田区大森西6-11-1', 'phone': '03-3762-4151', 'facility_type': 'hospital', 'beds': 832, 'website': 'https://www.omori.med.toho-u.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '東海大学医学部付属病院', 'prefecture': '神奈川県', 'address': '伊勢原市下糟屋143', 'phone': '0463-93-1121', 'facility_type': 'hospital', 'beds': 840, 'website': 'https://hospital.tokai-u.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '聖マリアンナ医科大学病院', 'prefecture': '神奈川県', 'address': '川崎市宮前区菅生2-16-1', 'phone': '044-977-8111', 'facility_type': 'hospital', 'beds': 1046, 'website': 'https://www.marianna-u.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '新潟大学医歯学総合病院', 'prefecture': '新潟県', 'address': '新潟市中央区旭町通一番町754', 'phone': '025-227-2555', 'facility_type': 'hospital', 'beds': 714, 'website': 'https://www.hosp.niigata-u.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '金沢大学附属病院', 'prefecture': '石川県', 'address': '金沢市宝町13-1', 'phone': '076-265-2000', 'facility_type': 'hospital', 'beds': 850, 'website': 'https://www.hosp.kanazawa-u.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子'},
    {'name': '福井大学医学部附属病院', 'prefecture': '福井県', 'address': '吉田郡永平寺町松岡下合月23-3', 'phone': '0776-61-3111', 'facility_type': 'hospital', 'beds': 612, 'website': 'https://www.hosp.u-fukui.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '信州大学医学部附属病院', 'prefecture': '長野県', 'address': '松本市旭3-1-1', 'phone': '0263-35-3600', 'facility_type': 'hospital', 'beds': 730, 'website': 'https://www.shinshu-u.ac.jp/faculty/medicine/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '浜松医科大学医学部附属病院', 'prefecture': '静岡県', 'address': '浜松市中央区半田山1-20-1', 'phone': '053-435-2111', 'facility_type': 'hospital', 'beds': 612, 'website': 'https://hama-hosp.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '藤田医科大学病院', 'prefecture': '愛知県', 'address': '豊明市沓掛町田楽ヶ窪1-98', 'phone': '0562-93-2111', 'facility_type': 'hospital', 'beds': 1424, 'website': 'https://hospital.fujita-hu.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子'},
    {'name': '愛知医科大学病院', 'prefecture': '愛知県', 'address': '長久手市岩作雁又1-1', 'phone': '0561-62-3311', 'facility_type': 'hospital', 'beds': 850, 'website': 'https://www.aichi-med-u.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '三重大学医学部附属病院', 'prefecture': '三重県', 'address': '津市江戸橋2-174', 'phone': '059-232-1111', 'facility_type': 'hospital', 'beds': 702, 'website': 'https://www.hosp.mie-u.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '滋賀医科大学医学部附属病院', 'prefecture': '滋賀県', 'address': '大津市瀬田月輪町', 'phone': '077-548-2111', 'facility_type': 'hospital', 'beds': 612, 'website': 'https://www.sums.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '奈良県立医科大学附属病院', 'prefecture': '奈良県', 'address': '橿原市四条町840', 'phone': '0744-22-3051', 'facility_type': 'hospital', 'beds': 912, 'website': 'https://www.naramed-u.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '和歌山県立医科大学附属病院', 'prefecture': '和歌山県', 'address': '和歌山市紀三井寺811-1', 'phone': '073-447-2300', 'facility_type': 'hospital', 'beds': 829, 'website': 'https://www.wakayama-med.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '鳥取大学医学部附属病院', 'prefecture': '鳥取県', 'address': '米子市西町36-1', 'phone': '0859-33-1111', 'facility_type': 'hospital', 'beds': 716, 'website': 'https://www2.hosp.med.tottori-u.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '島根大学医学部附属病院', 'prefecture': '島根県', 'address': '出雲市塩冶町89-1', 'phone': '0853-23-2111', 'facility_type': 'hospital', 'beds': 636, 'website': 'https://www.hosp.shimane-u.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '岡山大学病院', 'prefecture': '岡山県', 'address': '岡山市北区鹿田町2-5-1', 'phone': '086-223-7151', 'facility_type': 'hospital', 'beds': 827, 'website': 'https://www.okayama-u.ac.jp/user/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子'},
    {'name': '山口大学医学部附属病院', 'prefecture': '山口県', 'address': '宇部市南小串1-1-1', 'phone': '0836-22-2111', 'facility_type': 'hospital', 'beds': 714, 'website': 'https://www.hosp.yamaguchi-u.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '徳島大学病院', 'prefecture': '徳島県', 'address': '徳島市蔵本町2-50-1', 'phone': '088-631-3111', 'facility_type': 'hospital', 'beds': 718, 'website': 'https://www.hosp.tokushima-u.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '香川大学医学部附属病院', 'prefecture': '香川県', 'address': '木田郡三木町池戸1750-1', 'phone': '087-898-5111', 'facility_type': 'hospital', 'beds': 636, 'website': 'https://www.kms.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '愛媛大学医学部附属病院', 'prefecture': '愛媛県', 'address': '東温市志津川454', 'phone': '089-964-5111', 'facility_type': 'hospital', 'beds': 700, 'website': 'https://www.hosp.ehime-u.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '高知大学医学部附属病院', 'prefecture': '高知県', 'address': '南国市岡豊町小蓮185-1', 'phone': '088-866-5811', 'facility_type': 'hospital', 'beds': 612, 'website': 'https://www.kochi-u.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '産業医科大学病院', 'prefecture': '福岡県', 'address': '北九州市八幡西区医生ヶ丘1-1', 'phone': '093-603-1611', 'facility_type': 'hospital', 'beds': 848, 'website': 'https://www.uoeh-u.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科,労働衛生', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '佐賀大学医学部附属病院', 'prefecture': '佐賀県', 'address': '佐賀市鍋島5-1-1', 'phone': '0952-31-6511', 'facility_type': 'hospital', 'beds': 636, 'website': 'https://www.saga-u.ac.jp/soshiki/igaku/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '長崎大学病院', 'prefecture': '長崎県', 'address': '長崎市坂本1-7-1', 'phone': '095-819-7200', 'facility_type': 'hospital', 'beds': 786, 'website': 'https://www.mh.nagasaki-u.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '熊本大学病院', 'prefecture': '熊本県', 'address': '熊本市中央区本荘1-1-1', 'phone': '096-344-2111', 'facility_type': 'hospital', 'beds': 893, 'website': 'https://www.hosp.kumamoto-u.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子'},
    {'name': '大分大学医学部附属病院', 'prefecture': '大分県', 'address': '由布市挾間町医大ヶ丘1-1', 'phone': '097-549-4411', 'facility_type': 'hospital', 'beds': 612, 'website': 'https://www.med.oita-u.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '宮崎大学医学部附属病院', 'prefecture': '宮崎県', 'address': '宮崎市清武町木花台西1-1', 'phone': '0985-85-1510', 'facility_type': 'hospital', 'beds': 636, 'website': 'https://www.med.miyazaki-u.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '鹿児島大学病院', 'prefecture': '鹿児島県', 'address': '鹿児島市桜ヶ丘8-35-1', 'phone': '099-275-5111', 'facility_type': 'hospital', 'beds': 830, 'website': 'https://www.kufm.kagoshima-u.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '琉球大学病院', 'prefecture': '沖縄県', 'address': '中頭郡西原町字上原207', 'phone': '098-895-3331', 'facility_type': 'hospital', 'beds': 636, 'website': 'https://hosp.u-ryukyu.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    # ── 国立病院機構（残り全施設）──────────────────
    {'name': '国立病院機構 岩手病院', 'prefecture': '岩手県', 'address': '二戸市堀野大川目21-1', 'phone': '0195-23-2191', 'facility_type': 'hospital', 'beds': 230, 'website': 'https://iwate.hosp.go.jp/', 'departments': '内科,外科,整形外科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 花巻病院', 'prefecture': '岩手県', 'address': '花巻市円万寺22-1', 'phone': '0198-23-3131', 'facility_type': 'hospital', 'beds': 200, 'website': 'https://hanamaki.hosp.go.jp/', 'departments': '内科,外科,精神科,神経内科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 山形病院', 'prefecture': '山形県', 'address': '東村山郡山辺町大字山辺1800', 'phone': '023-664-2301', 'facility_type': 'hospital', 'beds': 260, 'website': 'https://yamagata.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 米沢病院', 'prefecture': '山形県', 'address': '米沢市川井2938', 'phone': '0238-22-3666', 'facility_type': 'hospital', 'beds': 200, 'website': 'https://yonezawa.hosp.go.jp/', 'departments': '内科,外科,整形外科,神経内科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 福島病院', 'prefecture': '福島県', 'address': '石川郡石川町字双里1-1', 'phone': '0247-26-3151', 'facility_type': 'hospital', 'beds': 280, 'website': 'https://fukushima.hosp.go.jp/', 'departments': '内科,外科,整形外科,リハビリ科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 西埼玉中央病院', 'prefecture': '埼玉県', 'address': '所沢市大字上安松1197', 'phone': '04-2995-1500', 'facility_type': 'hospital', 'beds': 310, 'website': 'https://nishi-saitama.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 埼玉病院', 'prefecture': '埼玉県', 'address': '和光市諏訪2-1', 'phone': '048-462-1101', 'facility_type': 'hospital', 'beds': 350, 'website': 'https://saitama.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 富山病院', 'prefecture': '富山県', 'address': '砺波市太郎丸100', 'phone': '0763-32-3190', 'facility_type': 'hospital', 'beds': 280, 'website': 'https://toyama.hosp.go.jp/', 'departments': '内科,外科,整形外科,リハビリ科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 松本医療センター', 'prefecture': '長野県', 'address': '松本市大字村井町南3-20-1', 'phone': '0263-58-4567', 'facility_type': 'hospital', 'beds': 330, 'website': 'https://matsumoto.hosp.go.jp/', 'departments': '内科,外科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 岐阜医療センター', 'prefecture': '岐阜県', 'address': '岐阜市野一色4-6-1', 'phone': '058-241-7321', 'facility_type': 'hospital', 'beds': 400, 'website': 'https://gifu.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 愛知医療センター名古屋第一病院', 'prefecture': '愛知県', 'address': '名古屋市西区平野区1', 'phone': '052-523-7711', 'facility_type': 'hospital', 'beds': 660, 'website': 'https://nagoya1.hosp.go.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 愛知医療センター名古屋第二病院', 'prefecture': '愛知県', 'address': '名古屋市東区代官町2-52', 'phone': '052-931-7141', 'facility_type': 'hospital', 'beds': 602, 'website': 'https://nagoya2.hosp.go.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 愛知医療センター春日井病院', 'prefecture': '愛知県', 'address': '春日井市松新町1-1-10', 'phone': '0568-84-0077', 'facility_type': 'hospital', 'beds': 354, 'website': 'https://kasugai.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 近江病院', 'prefecture': '滋賀県', 'address': '東近江市石塚町820', 'phone': '0748-22-5511', 'facility_type': 'hospital', 'beds': 290, 'website': 'https://ohmi.hosp.go.jp/', 'departments': '内科,外科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 和歌山病院', 'prefecture': '和歌山県', 'address': '和歌山市秋月580', 'phone': '073-471-2391', 'facility_type': 'hospital', 'beds': 250, 'website': 'https://wakayama.hosp.go.jp/', 'departments': '内科,外科,整形外科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 島根医療センター', 'prefecture': '島根県', 'address': '大田市大田町大田1227-1', 'phone': '0854-82-0900', 'facility_type': 'hospital', 'beds': 330, 'website': 'https://shimane.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 徳島病院', 'prefecture': '徳島県', 'address': '吉野川市鴨島町敷地1番地1', 'phone': '0883-24-2161', 'facility_type': 'hospital', 'beds': 240, 'website': 'https://tokushima.hosp.go.jp/', 'departments': '内科,外科,整形外科,神経内科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 高知病院', 'prefecture': '高知県', 'address': '高知市朝倉西町1-2-25', 'phone': '088-844-1111', 'facility_type': 'hospital', 'beds': 370, 'website': 'https://kochi.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 佐賀病院', 'prefecture': '佐賀県', 'address': '佐賀市巨勢町大字牛島500', 'phone': '0952-30-7141', 'facility_type': 'hospital', 'beds': 320, 'website': 'https://saga.hosp.go.jp/', 'departments': '内科,外科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 宮崎病院', 'prefecture': '宮崎県', 'address': '宮崎市佐土原町下那珂16500', 'phone': '0985-73-4161', 'facility_type': 'hospital', 'beds': 310, 'website': 'https://miyazaki.hosp.go.jp/', 'departments': '内科,外科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    # ── 赤十字病院（残り全施設）────────────────────
    {'name': '釧路赤十字病院', 'prefecture': '北海道', 'address': '釧路市新栄町21-14', 'phone': '0154-22-7171', 'facility_type': 'hospital', 'beds': 377, 'website': 'https://www.kushiro.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '北見赤十字病院', 'prefecture': '北海道', 'address': '北見市北4条東2丁目', 'phone': '0157-24-3115', 'facility_type': 'hospital', 'beds': 432, 'website': 'https://www.kitami.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '盛岡赤十字病院', 'prefecture': '岩手県', 'address': '盛岡市三本柳6-1-1', 'phone': '019-637-3111', 'facility_type': 'hospital', 'beds': 380, 'website': 'https://www.morioka.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '石巻赤十字病院', 'prefecture': '宮城県', 'address': '石巻市蛇田字西道下71', 'phone': '0225-21-7220', 'facility_type': 'hospital', 'beds': 320, 'website': 'https://www.ishinomaki.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '福島赤十字病院', 'prefecture': '福島県', 'address': '福島市入江町11-25', 'phone': '024-534-6101', 'facility_type': 'hospital', 'beds': 350, 'website': 'https://www.fukushima.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '水戸赤十字病院', 'prefecture': '茨城県', 'address': '水戸市三の丸3-12-48', 'phone': '029-221-5454', 'facility_type': 'hospital', 'beds': 348, 'website': 'https://www.mito.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '足利赤十字病院', 'prefecture': '栃木県', 'address': '足利市五十部町284-1', 'phone': '0284-21-0121', 'facility_type': 'hospital', 'beds': 450, 'website': 'https://www.ashikaga.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '深谷赤十字病院', 'prefecture': '埼玉県', 'address': '深谷市上柴町西5-8-1', 'phone': '048-571-1511', 'facility_type': 'hospital', 'beds': 408, 'website': 'https://www.fukaya.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '名古屋第二赤十字病院', 'prefecture': '愛知県', 'address': '名古屋市昭和区妙見町2-9', 'phone': '052-832-1121', 'facility_type': 'hospital', 'beds': 640, 'website': 'https://www.nagoya2.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '伊勢赤十字病院', 'prefecture': '三重県', 'address': '伊勢市船江1-471-2', 'phone': '0596-28-2171', 'facility_type': 'hospital', 'beds': 538, 'website': 'https://www.ise.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '舞鶴赤十字病院', 'prefecture': '京都府', 'address': '舞鶴市字浜2130', 'phone': '0773-75-2555', 'facility_type': 'hospital', 'beds': 440, 'website': 'https://www.maizuru.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '岡山赤十字病院', 'prefecture': '岡山県', 'address': '岡山市北区青江2-1-1', 'phone': '086-222-8811', 'facility_type': 'hospital', 'beds': 383, 'website': 'https://www.okayama.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '山口赤十字病院', 'prefecture': '山口県', 'address': '山口市八幡馬場23-1', 'phone': '083-923-0111', 'facility_type': 'hospital', 'beds': 430, 'website': 'https://www.yamaguchi.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '佐賀赤十字病院', 'prefecture': '佐賀県', 'address': '佐賀市大財4-13-1', 'phone': '0952-24-4386', 'facility_type': 'hospital', 'beds': 252, 'website': 'https://www.saga.jrc.or.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '大分赤十字病院', 'prefecture': '大分県', 'address': '大分市千代町3-2-37', 'phone': '097-532-6181', 'facility_type': 'hospital', 'beds': 502, 'website': 'https://www.oita.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '宮崎赤十字病院', 'prefecture': '宮崎県', 'address': '宮崎市丸山2-5-45', 'phone': '0985-23-4101', 'facility_type': 'hospital', 'beds': 300, 'website': 'https://www.miyazaki.jrc.or.jp/', 'departments': '内科,外科,小児科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '沖縄赤十字病院', 'prefecture': '沖縄県', 'address': '那覇市与儀1-3-1', 'phone': '098-853-3134', 'facility_type': 'hospital', 'beds': 250, 'website': 'https://www.okinawa.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    # ── 済生会（残り全施設）────────────────────────
    {'name': '済生会岩手病院', 'prefecture': '岩手県', 'address': '奥州市水沢区龍ケ馬場4', 'phone': '0197-24-4121', 'facility_type': 'hospital', 'beds': 310, 'website': 'https://www.saiseikai-iwate.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会山形済生病院', 'prefecture': '山形県', 'address': '山形市沖町79-1', 'phone': '023-682-1111', 'facility_type': 'hospital', 'beds': 461, 'website': 'https://www.saiseikai-yamagata.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会福島総合病院', 'prefecture': '福島県', 'address': '福島市八島田1-1-2', 'phone': '024-522-7211', 'facility_type': 'hospital', 'beds': 355, 'website': 'https://www.saiseikai-fukushima.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会宇都宮病院', 'prefecture': '栃木県', 'address': '宇都宮市竹林町911-1', 'phone': '028-626-5500', 'facility_type': 'hospital', 'beds': 476, 'website': 'https://www.saisei-u.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会栗橋病院', 'prefecture': '埼玉県', 'address': '久喜市小右衛門531', 'phone': '0480-52-3611', 'facility_type': 'hospital', 'beds': 260, 'website': 'https://www.saiseikai-kurihashi.jp/', 'departments': '内科,外科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会千葉病院', 'prefecture': '千葉県', 'address': '千葉市中央区新町2-1', 'phone': '043-227-2551', 'facility_type': 'hospital', 'beds': 340, 'website': 'https://www.saiseikai-chiba.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会横浜市南部病院', 'prefecture': '神奈川県', 'address': '横浜市港南区上大岡西2-15-1', 'phone': '045-832-1111', 'facility_type': 'hospital', 'beds': 430, 'website': 'https://www.saiseikai-yokohamashi-nanbu.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会富山病院', 'prefecture': '富山県', 'address': '富山市今市基田130', 'phone': '076-437-1123', 'facility_type': 'hospital', 'beds': 350, 'website': 'https://www.saiseikai-toyama.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会石川総合病院', 'prefecture': '石川県', 'address': '野々市市押野2-65', 'phone': '076-246-8000', 'facility_type': 'hospital', 'beds': 500, 'website': 'https://www.saiseikai-ishikawa.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会静岡病院', 'prefecture': '静岡県', 'address': '静岡市駿河区小鹿一丁目1-1', 'phone': '054-285-6171', 'facility_type': 'hospital', 'beds': 350, 'website': 'https://www.saiseikai-shizuoka.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会岐阜病院', 'prefecture': '岐阜県', 'address': '岐阜市鷺山向井2086', 'phone': '058-231-2626', 'facility_type': 'hospital', 'beds': 300, 'website': 'https://www.saiseikai-gifu.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会三重病院', 'prefecture': '三重県', 'address': '松阪市高町795', 'phone': '0598-51-2626', 'facility_type': 'hospital', 'beds': 350, 'website': 'https://www.saiseikai-mie.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会京都府病院', 'prefecture': '京都府', 'address': '向日市鶏冠井町大極殿1', 'phone': '075-922-1811', 'facility_type': 'hospital', 'beds': 456, 'website': 'https://www.saiseikai-kyotofubyoin.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会大阪病院', 'prefecture': '大阪府', 'address': '大阪市西区本田1-2-7', 'phone': '06-6581-1531', 'facility_type': 'hospital', 'beds': 420, 'website': 'https://www.saiseikai-osaka.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会吹田病院', 'prefecture': '大阪府', 'address': '吹田市川岸町1-21', 'phone': '06-6382-6600', 'facility_type': 'hospital', 'beds': 350, 'website': 'https://www.saiseikai-suita.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会兵庫県病院', 'prefecture': '兵庫県', 'address': '神戸市兵庫区西柳原町12-23', 'phone': '078-511-6111', 'facility_type': 'hospital', 'beds': 360, 'website': 'https://www.saiseikai-hyogo.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会岡山病院', 'prefecture': '岡山県', 'address': '岡山市北区国体町2-25', 'phone': '086-252-2211', 'facility_type': 'hospital', 'beds': 350, 'website': 'https://www.saiseikai-okayama.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会広島病院', 'prefecture': '広島県', 'address': '廿日市市地御前1-1-1', 'phone': '0829-36-5500', 'facility_type': 'hospital', 'beds': 420, 'website': 'https://www.saiseikai-hiroshima.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会山口総合病院', 'prefecture': '山口県', 'address': '山口市緑町2-10', 'phone': '083-922-2525', 'facility_type': 'hospital', 'beds': 400, 'website': 'https://www.saiseikai-yamaguchi.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会高知病院', 'prefecture': '高知県', 'address': '高知市孕東町2-1-57', 'phone': '088-822-1555', 'facility_type': 'hospital', 'beds': 250, 'website': 'https://www.saiseikai-kochi.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会佐賀病院', 'prefecture': '佐賀県', 'address': '佐賀市鍋島3-6-11', 'phone': '0952-24-2131', 'facility_type': 'hospital', 'beds': 300, 'website': 'https://www.saiseikai-saga.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会長崎病院', 'prefecture': '長崎県', 'address': '長崎市松山町37', 'phone': '095-861-2321', 'facility_type': 'hospital', 'beds': 300, 'website': 'https://www.saiseikai-nagasaki.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会大分病院', 'prefecture': '大分県', 'address': '大分市新春日浦1-1', 'phone': '097-552-0411', 'facility_type': 'hospital', 'beds': 300, 'website': 'https://www.saiseikai-oita.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会宮崎病院', 'prefecture': '宮崎県', 'address': '宮崎市新別府町浜の前当3020', 'phone': '0985-24-9567', 'facility_type': 'hospital', 'beds': 300, 'website': 'https://www.saiseikai-miyazaki.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    # ── JA厚生連（主要全施設）──────────────────────
    {'name': 'JA北海道厚生連 帯広厚生病院', 'prefecture': '北海道', 'address': '帯広市西6条南8丁目1-1', 'phone': '0155-22-4165', 'facility_type': 'hospital', 'beds': 420, 'website': 'https://www.obihiro-kosei.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA北海道厚生連 旭川厚生病院', 'prefecture': '北海道', 'address': '旭川市1条通24丁目111番地3', 'phone': '0166-33-7171', 'facility_type': 'hospital', 'beds': 320, 'website': 'https://www.asahikawa-kosei.or.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA秋田厚生連 秋田厚生医療センター', 'prefecture': '秋田県', 'address': '秋田市手形字菅谷地8-65', 'phone': '018-823-4171', 'facility_type': 'hospital', 'beds': 312, 'website': 'https://www.akita-kosei.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA山形厚生連 日本海総合病院', 'prefecture': '山形県', 'address': '酒田市新橋64', 'phone': '0234-26-5000', 'facility_type': 'hospital', 'beds': 612, 'website': 'https://www.nihonkai-hosp.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA山形厚生連 山形厚生病院', 'prefecture': '山形県', 'address': '東村山郡中山町大字長崎5765-1', 'phone': '023-662-2111', 'facility_type': 'hospital', 'beds': 350, 'website': 'https://www.yamagata-kosei.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA福島厚生連 白河厚生総合病院', 'prefecture': '福島県', 'address': '白河市豊地須賀川字日向100', 'phone': '0248-23-3321', 'facility_type': 'hospital', 'beds': 450, 'website': 'https://www.shirakawa-kosei.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA福島厚生連 福島厚生病院', 'prefecture': '福島県', 'address': '郡山市大町1-7-13', 'phone': '024-922-1340', 'facility_type': 'hospital', 'beds': 310, 'website': 'https://www.fukushima-kosei.or.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA茨城県厚生連 JAとりで総合医療センター', 'prefecture': '茨城県', 'address': '取手市本郷2-1-1', 'phone': '0297-74-5551', 'facility_type': 'hospital', 'beds': 440, 'website': 'https://www.ja-ibaraki-kousei.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA栃木厚生連 上都賀総合病院', 'prefecture': '栃木県', 'address': '鹿沼市中田町1-1069', 'phone': '0289-65-1121', 'facility_type': 'hospital', 'beds': 350, 'website': 'https://www.kamitsuga.or.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA群馬厚生連 群馬厚生病院', 'prefecture': '群馬県', 'address': '渋川市白井367-1', 'phone': '0279-22-4321', 'facility_type': 'hospital', 'beds': 400, 'website': 'https://www.gumma-kosei.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA埼玉県厚生連 久喜総合病院', 'prefecture': '埼玉県', 'address': '久喜市久喜中央1-4-37', 'phone': '0480-21-5151', 'facility_type': 'hospital', 'beds': 475, 'website': 'https://www.jakosei.or.jp/kuki/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA埼玉県厚生連 熊谷総合病院', 'prefecture': '埼玉県', 'address': '熊谷市中西4-5-1', 'phone': '048-521-0065', 'facility_type': 'hospital', 'beds': 405, 'website': 'https://www.jakosei.or.jp/kumagaya/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA千葉厚生連 旭中央病院', 'prefecture': '千葉県', 'address': '旭市イ1326', 'phone': '0479-63-8111', 'facility_type': 'hospital', 'beds': 880, 'website': 'https://www.asahichuo.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子'},
    {'name': 'JA千葉厚生連 安房地域医療センター', 'prefecture': '千葉県', 'address': '館山市山本1310', 'phone': '0470-22-3606', 'facility_type': 'hospital', 'beds': 320, 'website': 'https://www.awa-chiiki.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA新潟厚生連 長岡中央綜合病院', 'prefecture': '新潟県', 'address': '長岡市川崎町2041', 'phone': '0258-35-0011', 'facility_type': 'hospital', 'beds': 600, 'website': 'https://www.nagaokachuo.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA新潟厚生連 上越総合病院', 'prefecture': '新潟県', 'address': '上越市大字南城2610-1', 'phone': '025-522-2000', 'facility_type': 'hospital', 'beds': 430, 'website': 'https://www.joetsu-general.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA石川県厚生連 公立松任石川中央病院', 'prefecture': '石川県', 'address': '白山市徳光町1-1', 'phone': '076-276-1011', 'facility_type': 'hospital', 'beds': 320, 'website': 'https://www.mattou-hospital.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA長野厚生連 長野松代総合病院', 'prefecture': '長野県', 'address': '長野市松代町松代635', 'phone': '026-278-2481', 'facility_type': 'hospital', 'beds': 280, 'website': 'https://www.nk-hospital.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA長野厚生連 北アルプス医療センターあづみ病院', 'prefecture': '長野県', 'address': '北安曇郡池田町大字池田1750', 'phone': '0261-62-2261', 'facility_type': 'hospital', 'beds': 320, 'website': 'https://www.ja-nagano-koseiren.or.jp/azumi/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA静岡厚生連 静岡厚生病院', 'prefecture': '静岡県', 'address': '静岡市葵区北安東4-27-1', 'phone': '054-247-3700', 'facility_type': 'hospital', 'beds': 300, 'website': 'https://www.shizuoka-kosei.or.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA愛知厚生連 江南厚生病院', 'prefecture': '愛知県', 'address': '江南市高屋町大松21', 'phone': '0587-55-3411', 'facility_type': 'hospital', 'beds': 500, 'website': 'https://www.konan-kosei.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA愛知厚生連 豊田厚生病院', 'prefecture': '愛知県', 'address': '豊田市浄水町伊保原500-1', 'phone': '0565-43-5000', 'facility_type': 'hospital', 'beds': 612, 'website': 'https://www.toyota-kosei.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA三重厚生連 松阪中央総合病院', 'prefecture': '三重県', 'address': '松阪市川井町102', 'phone': '0598-51-2626', 'facility_type': 'hospital', 'beds': 480, 'website': 'https://www.matsusaka-chuo.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA三重厚生連 伊勢総合病院', 'prefecture': '三重県', 'address': '伊勢市楠部町136', 'phone': '0596-28-2171', 'facility_type': 'hospital', 'beds': 400, 'website': 'https://www.ise-hp.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA広島厚生連 尾道総合病院', 'prefecture': '広島県', 'address': '尾道市平原1-10-23', 'phone': '0848-22-8111', 'facility_type': 'hospital', 'beds': 600, 'website': 'https://www.onomichi-hp.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA広島厚生連 三次中央病院', 'prefecture': '広島県', 'address': '三次市十日市東4-9-1', 'phone': '0824-63-0111', 'facility_type': 'hospital', 'beds': 300, 'website': 'https://www.miyoshi-hp.or.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA岡山厚生連 津山中央病院', 'prefecture': '岡山県', 'address': '津山市川崎1756', 'phone': '0868-21-8111', 'facility_type': 'hospital', 'beds': 550, 'website': 'https://www.tsuyama-chuo.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA徳島厚生連 阿南共栄病院', 'prefecture': '徳島県', 'address': '阿南市富岡町トノ町2-1', 'phone': '0884-22-3301', 'facility_type': 'hospital', 'beds': 280, 'website': 'https://www.anankyouei.or.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA香川厚生連 滝宮総合病院', 'prefecture': '香川県', 'address': '綾歌郡綾川町滝宮1899', 'phone': '087-876-0111', 'facility_type': 'hospital', 'beds': 420, 'website': 'https://www.takinomiya.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA香川厚生連 屋島総合病院', 'prefecture': '香川県', 'address': '高松市屋島西町1-1', 'phone': '087-844-0040', 'facility_type': 'hospital', 'beds': 300, 'website': 'https://www.yashima-hp.or.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA高知病院', 'prefecture': '高知県', 'address': '高知市介良乙1855', 'phone': '088-847-2222', 'facility_type': 'hospital', 'beds': 350, 'website': 'https://www.ja-kochi.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA福岡厚生連 直方中間地区医療センター 直方病院', 'prefecture': '福岡県', 'address': '直方市山部347-1', 'phone': '0949-22-0022', 'facility_type': 'hospital', 'beds': 280, 'website': 'https://www.ja-fk.or.jp/', 'departments': '内科,外科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA熊本厚生連 熊本総合病院', 'prefecture': '熊本県', 'address': '宇城市松橋町松橋540', 'phone': '0964-32-1131', 'facility_type': 'hospital', 'beds': 350, 'website': 'https://www.ja-kumamoto.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA宮崎厚生連 宮崎江南病院', 'prefecture': '宮崎県', 'address': '宮崎市大橋1-4-1', 'phone': '0985-51-1571', 'facility_type': 'hospital', 'beds': 250, 'website': 'https://www.miyazaki-konan.or.jp/', 'departments': '内科,外科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    # ── 徳洲会（残り全施設）────────────────────────
    {'name': '旭川徳洲会病院', 'prefecture': '北海道', 'address': '旭川市永山8条19丁目6-1', 'phone': '0166-48-1000', 'facility_type': 'hospital', 'beds': 260, 'website': 'https://asahikawa.tokushukai.or.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '帯広徳洲会病院', 'prefecture': '北海道', 'address': '帯広市東14条南18丁目2', 'phone': '0155-25-1000', 'facility_type': 'hospital', 'beds': 260, 'website': 'https://obihiro.tokushukai.or.jp/', 'departments': '内科,外科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '湘南藤沢徳洲会病院', 'prefecture': '神奈川県', 'address': '藤沢市遠藤4257-1', 'phone': '0466-35-1177', 'facility_type': 'hospital', 'beds': 320, 'website': 'https://shonan-fujisawa.tokushukai.or.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '東京西徳洲会病院', 'prefecture': '東京都', 'address': '昭島市拝島町4-3-1', 'phone': '042-543-8111', 'facility_type': 'hospital', 'beds': 320, 'website': 'https://tokyonishi.tokushukai.or.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '八尾徳洲会総合病院', 'prefecture': '大阪府', 'address': '八尾市龍華町1-3-1', 'phone': '072-948-2500', 'facility_type': 'hospital', 'beds': 360, 'website': 'https://yao.tokushukai.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '野崎徳洲会病院', 'prefecture': '大阪府', 'address': '大東市中垣内5-2-10', 'phone': '072-875-0374', 'facility_type': 'hospital', 'beds': 330, 'website': 'https://nozaki.tokushukai.or.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '宇治徳洲会病院', 'prefecture': '京都府', 'address': '宇治市伊勢田町猿渡152-1', 'phone': '0774-22-1103', 'facility_type': 'hospital', 'beds': 240, 'website': 'https://uji.tokushukai.or.jp/', 'departments': '内科,外科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '鳴門徳洲会病院', 'prefecture': '徳島県', 'address': '鳴門市撫養町南浜字東浜230-2', 'phone': '088-685-0777', 'facility_type': 'hospital', 'beds': 260, 'website': 'https://naruto.tokushukai.or.jp/', 'departments': '内科,外科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '古賀病院21', 'prefecture': '福岡県', 'address': '久留米市天神町120', 'phone': '0942-38-2222', 'facility_type': 'hospital', 'beds': 710, 'website': 'https://koga21.tokushukai.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '中部徳洲会病院', 'prefecture': '沖縄県', 'address': '中頭郡北谷町北前1-14-1', 'phone': '098-936-1057', 'facility_type': 'hospital', 'beds': 350, 'website': 'https://chubu.tokushukai.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '南部徳洲会病院', 'prefecture': '沖縄県', 'address': '島尻郡八重瀬町字仲座487', 'phone': '098-998-3221', 'facility_type': 'hospital', 'beds': 250, 'website': 'https://nanbu.tokushukai.or.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '宮古島徳洲会病院', 'prefecture': '沖縄県', 'address': '宮古島市平良字東仲宗根537-9', 'phone': '0980-73-1100', 'facility_type': 'hospital', 'beds': 200, 'website': 'https://miyakojima.tokushukai.or.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    # ── 民間・特定機能病院 ──────────────────────────
    {'name': '聖路加国際病院', 'prefecture': '東京都', 'address': '東京都中央区明石町9-1', 'phone': '03-3541-5151', 'facility_type': 'hospital', 'beds': 520, 'website': 'https://hospital.luke.ac.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子'},
    {'name': '虎の門病院', 'prefecture': '東京都', 'address': '東京都港区虎ノ門2-2-2', 'phone': '03-3588-1111', 'facility_type': 'hospital', 'beds': 856, 'website': 'https://www.toranomon.gr.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子'},
    {'name': '国立がん研究センター中央病院', 'prefecture': '東京都', 'address': '東京都中央区築地5-1-1', 'phone': '03-3542-2511', 'facility_type': 'hospital', 'beds': 756, 'website': 'https://www.ncc.go.jp/jp/ncch/', 'departments': '腫瘍内科,外科,放射線科,緩和医療科', 'inspection_items': '血液,生化学,免疫,微生物,病理,遺伝子'},
    {'name': '国立がん研究センター東病院', 'prefecture': '千葉県', 'address': '柏市柏の葉6-5-1', 'phone': '04-7133-1111', 'facility_type': 'hospital', 'beds': 500, 'website': 'https://www.ncc.go.jp/jp/ncce/', 'departments': '腫瘍内科,外科,放射線科,緩和医療科', 'inspection_items': '血液,生化学,免疫,微生物,病理,遺伝子'},
    {'name': '癌研有明病院', 'prefecture': '東京都', 'address': '東京都江東区有明3-8-31', 'phone': '03-3520-0111', 'facility_type': 'hospital', 'beds': 714, 'website': 'https://www.jfcr.or.jp/hospital/', 'departments': '腫瘍内科,外科,放射線科,消化器内科', 'inspection_items': '血液,生化学,免疫,微生物,病理,遺伝子'},
    {'name': '北里大学病院', 'prefecture': '神奈川県', 'address': '相模原市南区北里1-15-1', 'phone': '042-778-8111', 'facility_type': 'hospital', 'beds': 980, 'website': 'https://www.kitasato-u.ac.jp/khp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子'},
    {'name': '関西医科大学附属病院', 'prefecture': '大阪府', 'address': '枚方市新町2-3-1', 'phone': '072-804-0101', 'facility_type': 'hospital', 'beds': 918, 'website': 'https://www.kmu.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '大阪医科薬科大学病院', 'prefecture': '大阪府', 'address': '高槻市大学町2-7', 'phone': '072-683-1221', 'facility_type': 'hospital', 'beds': 900, 'website': 'https://www.ompu.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '兵庫医科大学病院', 'prefecture': '兵庫県', 'address': '西宮市武庫川町1-1', 'phone': '0798-45-6111', 'facility_type': 'hospital', 'beds': 920, 'website': 'https://www.hyo-med.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '川崎医科大学附属病院', 'prefecture': '岡山県', 'address': '倉敷市松島577', 'phone': '086-462-1111', 'facility_type': 'hospital', 'beds': 1100, 'website': 'https://www.kawasaki-m.ac.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    # ── 国立病院機構（追加）──────────────────────────
    {'name': '国立病院機構 北海道医療センター', 'prefecture': '北海道', 'address': '札幌市西区山の手5条7丁目1-1', 'phone': '011-611-8111', 'facility_type': 'hospital', 'beds': 510, 'website': 'https://hokkaido.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 弘前病院', 'prefecture': '青森県', 'address': '弘前市大字富野町1', 'phone': '0172-32-7512', 'facility_type': 'hospital', 'beds': 270, 'website': 'https://hirosaki.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 仙台西多賀病院', 'prefecture': '宮城県', 'address': '仙台市太白区鈎取本町2-11-11', 'phone': '022-245-5111', 'facility_type': 'hospital', 'beds': 310, 'website': 'https://sendai-nishitaga.hosp.go.jp/', 'departments': '内科,外科,整形外科,リハビリ科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 秋田病院', 'prefecture': '秋田県', 'address': '秋田市添川字添川17', 'phone': '018-836-3135', 'facility_type': 'hospital', 'beds': 250, 'website': 'https://akita.hosp.go.jp/', 'departments': '内科,外科,整形外科,リハビリ科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 水戸医療センター', 'prefecture': '茨城県', 'address': '東茨城郡茨城町桜の郷280', 'phone': '029-240-7711', 'facility_type': 'hospital', 'beds': 400, 'website': 'https://mito.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 栃木医療センター', 'prefecture': '栃木県', 'address': '宇都宮市中戸祭1-10-37', 'phone': '028-622-5241', 'facility_type': 'hospital', 'beds': 460, 'website': 'https://tochigi.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 高崎総合医療センター', 'prefecture': '群馬県', 'address': '高崎市高松町36', 'phone': '027-322-5901', 'facility_type': 'hospital', 'beds': 560, 'website': 'https://takasaki.hosp.go.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 千葉医療センター', 'prefecture': '千葉県', 'address': '千葉市中央区椿森4-1-2', 'phone': '043-251-5311', 'facility_type': 'hospital', 'beds': 460, 'website': 'https://chiba.hosp.go.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 東京病院', 'prefecture': '東京都', 'address': '東京都清瀬市竹丘3-1-1', 'phone': '042-491-2111', 'facility_type': 'hospital', 'beds': 530, 'website': 'https://tokyo.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 横浜医療センター', 'prefecture': '神奈川県', 'address': '横浜市戸塚区品濃町947', 'phone': '045-851-2621', 'facility_type': 'hospital', 'beds': 400, 'website': 'https://yokohama.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 新潟病院', 'prefecture': '新潟県', 'address': '柏崎市赤坂町3-52', 'phone': '0257-22-2126', 'facility_type': 'hospital', 'beds': 310, 'website': 'https://niigata.hosp.go.jp/', 'departments': '内科,外科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 金沢医療センター', 'prefecture': '石川県', 'address': '金沢市下石引町1-1', 'phone': '076-262-4161', 'facility_type': 'hospital', 'beds': 500, 'website': 'https://kanazawa.hosp.go.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 福井医療センター', 'prefecture': '福井県', 'address': '福井市四ツ井2-8-1', 'phone': '0776-36-3630', 'facility_type': 'hospital', 'beds': 385, 'website': 'https://fukui.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 静岡医療センター', 'prefecture': '静岡県', 'address': '駿東郡清水町長沢762-1', 'phone': '055-975-2000', 'facility_type': 'hospital', 'beds': 540, 'website': 'https://shizuoka.hosp.go.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 三重中央医療センター', 'prefecture': '三重県', 'address': '津市嬉野川北町1番地', 'phone': '059-232-3030', 'facility_type': 'hospital', 'beds': 340, 'website': 'https://mie-chuo.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 京都医療センター', 'prefecture': '京都府', 'address': '京都市伏見区深草向畑町1-1', 'phone': '075-641-9161', 'facility_type': 'hospital', 'beds': 580, 'website': 'https://kyoto.hosp.go.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 大阪南医療センター', 'prefecture': '大阪府', 'address': '河内長野市木戸東町2-1', 'phone': '0721-53-5761', 'facility_type': 'hospital', 'beds': 500, 'website': 'https://osaka-minami.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 姫路医療センター', 'prefecture': '兵庫県', 'address': '姫路市本町68', 'phone': '079-222-5101', 'facility_type': 'hospital', 'beds': 440, 'website': 'https://himeji.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 奈良医療センター', 'prefecture': '奈良県', 'address': '奈良市七条西町2-789', 'phone': '0742-46-0051', 'facility_type': 'hospital', 'beds': 350, 'website': 'https://nara.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 鳥取医療センター', 'prefecture': '鳥取県', 'address': '鳥取市江津730', 'phone': '0857-59-1111', 'facility_type': 'hospital', 'beds': 310, 'website': 'https://tottori.hosp.go.jp/', 'departments': '内科,外科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 岡山医療センター', 'prefecture': '岡山県', 'address': '岡山市北区田益1711-1', 'phone': '086-294-9911', 'facility_type': 'hospital', 'beds': 400, 'website': 'https://okayama.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 福山医療センター', 'prefecture': '広島県', 'address': '福山市沖野上町4-14-17', 'phone': '084-922-0001', 'facility_type': 'hospital', 'beds': 430, 'website': 'https://fukuyama.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 山口宇部医療センター', 'prefecture': '山口県', 'address': '宇部市南小串1-1-1', 'phone': '0836-22-2888', 'facility_type': 'hospital', 'beds': 390, 'website': 'https://yamaguchi-ube.hosp.go.jp/', 'departments': '内科,外科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 高松医療センター', 'prefecture': '香川県', 'address': '高松市番町2-11-29', 'phone': '087-831-3101', 'facility_type': 'hospital', 'beds': 360, 'website': 'https://takamatsu.hosp.go.jp/', 'departments': '内科,外科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 四国がんセンター', 'prefecture': '愛媛県', 'address': '松山市南梅本町甲160', 'phone': '089-999-1111', 'facility_type': 'hospital', 'beds': 300, 'website': 'https://shikoku-cc.hosp.go.jp/', 'departments': '腫瘍内科,外科,放射線科,緩和医療科', 'inspection_items': '血液,生化学,免疫,微生物,病理,遺伝子'},
    {'name': '国立病院機構 九州医療センター', 'prefecture': '福岡県', 'address': '福岡市中央区地行浜1-8-1', 'phone': '092-852-0700', 'facility_type': 'hospital', 'beds': 800, 'website': 'https://kyushu.hosp.go.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 長崎医療センター', 'prefecture': '長崎県', 'address': '東彼杵郡川棚町青い石郷2001-1', 'phone': '0956-82-8121', 'facility_type': 'hospital', 'beds': 480, 'website': 'https://nagasaki.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 熊本医療センター', 'prefecture': '熊本県', 'address': '熊本市中央区二の丸1-5', 'phone': '096-353-6501', 'facility_type': 'hospital', 'beds': 696, 'website': 'https://kumamoto.hosp.go.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 大分医療センター', 'prefecture': '大分県', 'address': '大分市大字横尾1sley358', 'phone': '097-582-1121', 'facility_type': 'hospital', 'beds': 460, 'website': 'https://oita.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 鹿児島医療センター', 'prefecture': '鹿児島県', 'address': '鹿児島市城山町8-1', 'phone': '099-223-1151', 'facility_type': 'hospital', 'beds': 500, 'website': 'https://kagoshima.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '国立病院機構 沖縄病院', 'prefecture': '沖縄県', 'address': '沖縄市字知花125', 'phone': '098-932-3116', 'facility_type': 'hospital', 'beds': 400, 'website': 'https://okinawa.hosp.go.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    # ── 赤十字病院（追加）──────────────────────────
    {'name': '旭川赤十字病院', 'prefecture': '北海道', 'address': '旭川市曙1条1丁目1-1', 'phone': '0166-22-8111', 'facility_type': 'hospital', 'beds': 573, 'website': 'https://www.asahikawa.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '秋田赤十字病院', 'prefecture': '秋田県', 'address': '秋田市上北手猿田字苗代沢222-1', 'phone': '018-829-5000', 'facility_type': 'hospital', 'beds': 428, 'website': 'https://www.akita.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '前橋赤十字病院', 'prefecture': '群馬県', 'address': '前橋市朝倉町389-1', 'phone': '027-265-3333', 'facility_type': 'hospital', 'beds': 634, 'website': 'https://www.maebashi.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'さいたま赤十字病院', 'prefecture': '埼玉県', 'address': 'さいたま市中央区新都心1-5', 'phone': '048-600-3333', 'facility_type': 'hospital', 'beds': 700, 'website': 'https://www.saitama-jrc.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '成田赤十字病院', 'prefecture': '千葉県', 'address': '成田市飯田町90-1', 'phone': '0476-22-2311', 'facility_type': 'hospital', 'beds': 622, 'website': 'https://www.narita.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '武蔵野赤十字病院', 'prefecture': '東京都', 'address': '東京都武蔵野市境南町1-26-1', 'phone': '0422-32-3111', 'facility_type': 'hospital', 'beds': 576, 'website': 'https://www.musashino.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '長岡赤十字病院', 'prefecture': '新潟県', 'address': '長岡市千秋2-297-1', 'phone': '0258-28-3600', 'facility_type': 'hospital', 'beds': 606, 'website': 'https://www.nagaoka.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '富山赤十字病院', 'prefecture': '富山県', 'address': '富山市牛島本町2-1-58', 'phone': '076-433-2222', 'facility_type': 'hospital', 'beds': 420, 'website': 'https://www.toyama.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '福井赤十字病院', 'prefecture': '福井県', 'address': '福井市月見2-4-1', 'phone': '0776-36-3366', 'facility_type': 'hospital', 'beds': 400, 'website': 'https://www.fukui.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '岐阜赤十字病院', 'prefecture': '岐阜県', 'address': '岐阜市岩倉町1-1', 'phone': '058-231-2266', 'facility_type': 'hospital', 'beds': 354, 'website': 'https://www.gifu.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '浜松赤十字病院', 'prefecture': '静岡県', 'address': '浜松市中央区蜆塚4-12-27', 'phone': '053-474-2111', 'facility_type': 'hospital', 'beds': 376, 'website': 'https://www.hamamatsu.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '京都第一赤十字病院', 'prefecture': '京都府', 'address': '京都市東山区本町15-749', 'phone': '075-561-1121', 'facility_type': 'hospital', 'beds': 588, 'website': 'https://www.kyoto1.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '神戸赤十字病院', 'prefecture': '兵庫県', 'address': '神戸市中央区脇浜海岸通1-3-1', 'phone': '078-231-5801', 'facility_type': 'hospital', 'beds': 412, 'website': 'https://www.kobe.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '高松赤十字病院', 'prefecture': '香川県', 'address': '高松市番町4-1-3', 'phone': '087-831-7101', 'facility_type': 'hospital', 'beds': 402, 'website': 'https://www.takamatsu.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '松山赤十字病院', 'prefecture': '愛媛県', 'address': '松山市文京町1', 'phone': '089-924-1111', 'facility_type': 'hospital', 'beds': 584, 'website': 'https://www.matsuyama.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '高知赤十字病院', 'prefecture': '高知県', 'address': '高知市九反田2-13-51', 'phone': '088-822-1201', 'facility_type': 'hospital', 'beds': 416, 'website': 'https://www.kochi.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '福岡赤十字病院', 'prefecture': '福岡県', 'address': '福岡市南区大楠3-1-1', 'phone': '092-521-4461', 'facility_type': 'hospital', 'beds': 500, 'website': 'https://www.fukuoka.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '熊本赤十字病院', 'prefecture': '熊本県', 'address': '熊本市東区長嶺南2-1-1', 'phone': '096-384-2111', 'facility_type': 'hospital', 'beds': 614, 'website': 'https://www.kumamoto.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '長崎原爆病院', 'prefecture': '長崎県', 'address': '長崎市橋口町3-15', 'phone': '095-844-1111', 'facility_type': 'hospital', 'beds': 295, 'website': 'https://www.nagasaki-jrc.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '鹿児島赤十字病院', 'prefecture': '鹿児島県', 'address': '鹿児島市鴨池2-36-1', 'phone': '099-252-0111', 'facility_type': 'hospital', 'beds': 350, 'website': 'https://www.kagoshima.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    # ── 都道府県立・市立病院 ────────────────────────
    {'name': '青森県立中央病院', 'prefecture': '青森県', 'address': '青森市東造道2-1-1', 'phone': '017-726-8111', 'facility_type': 'hospital', 'beds': 720, 'website': 'https://www.aomori-pref-chuo-hp.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '岩手県立中央病院', 'prefecture': '岩手県', 'address': '盛岡市上田4-3-60', 'phone': '019-653-1151', 'facility_type': 'hospital', 'beds': 792, 'website': 'https://www2.pref.iwate.jp/~hp0109/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '秋田県立中央病院', 'prefecture': '秋田県', 'address': '秋田市川元松丘町4-27', 'phone': '018-823-4171', 'facility_type': 'hospital', 'beds': 500, 'website': 'https://www.pref.akita.lg.jp/www/contents/1001000000071/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '山形県立中央病院', 'prefecture': '山形県', 'address': '山形市大字青柳1800', 'phone': '023-685-2626', 'facility_type': 'hospital', 'beds': 524, 'website': 'https://ychp.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '茨城県立中央病院', 'prefecture': '茨城県', 'address': '茨城町上石崎1-1', 'phone': '029-292-3111', 'facility_type': 'hospital', 'beds': 500, 'website': 'https://www.ibaraki-pref-chuo-hp.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '栃木県立がんセンター', 'prefecture': '栃木県', 'address': '宇都宮市陽南4-9-13', 'phone': '028-658-5151', 'facility_type': 'hospital', 'beds': 300, 'website': 'https://www.tochigi-cc.jp/', 'departments': '腫瘍内科,外科,放射線科,緩和医療科', 'inspection_items': '血液,生化学,免疫,微生物,病理,遺伝子'},
    {'name': '群馬県立がんセンター', 'prefecture': '群馬県', 'address': '太田市高林西町617-1', 'phone': '0276-38-0771', 'facility_type': 'hospital', 'beds': 300, 'website': 'https://www.gunma-cc.jp/', 'departments': '腫瘍内科,外科,放射線科,緩和医療科', 'inspection_items': '血液,生化学,免疫,微生物,病理,遺伝子'},
    {'name': '神奈川県立がんセンター', 'prefecture': '神奈川県', 'address': '横浜市旭区中尾2-3-2', 'phone': '045-520-2222', 'facility_type': 'hospital', 'beds': 500, 'website': 'https://www.kcch.jp/', 'departments': '腫瘍内科,外科,放射線科,緩和医療科', 'inspection_items': '血液,生化学,免疫,微生物,病理,遺伝子'},
    {'name': '新潟県立中央病院', 'prefecture': '新潟県', 'address': '上越市新南町777-1', 'phone': '025-522-7711', 'facility_type': 'hospital', 'beds': 680, 'website': 'https://www.pref.niigata.lg.jp/sec/chuohp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '富山県立中央病院', 'prefecture': '富山県', 'address': '富山市西長江2-2-78', 'phone': '076-424-1531', 'facility_type': 'hospital', 'beds': 700, 'website': 'https://www.pref-toyama-chp.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '石川県立中央病院', 'prefecture': '石川県', 'address': '金沢市鞍月東2-1', 'phone': '076-237-8211', 'facility_type': 'hospital', 'beds': 650, 'website': 'https://www.pref.ishikawa.lg.jp/chuo-hp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '静岡県立総合病院', 'prefecture': '静岡県', 'address': '静岡市葵区北安東4-27-1', 'phone': '054-247-6111', 'facility_type': 'hospital', 'beds': 780, 'website': 'https://www.seirei.or.jp/shizuoka/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '岐阜県総合医療センター', 'prefecture': '岐阜県', 'address': '岐阜市野一色4-6-1', 'phone': '058-246-1111', 'facility_type': 'hospital', 'beds': 700, 'website': 'https://www.ghsmc.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '三重県立総合医療センター', 'prefecture': '三重県', 'address': '四日市市大字日永5450-132', 'phone': '059-345-2321', 'facility_type': 'hospital', 'beds': 580, 'website': 'https://www.mie-chuo-mc.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '滋賀県立総合病院', 'prefecture': '滋賀県', 'address': '守山市守山5-4-30', 'phone': '077-582-5031', 'facility_type': 'hospital', 'beds': 626, 'website': 'https://www.shiga-pref-hospital.gr.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '島根県立中央病院', 'prefecture': '島根県', 'address': '出雲市姫原4-1-1', 'phone': '0853-22-5111', 'facility_type': 'hospital', 'beds': 660, 'website': 'https://www.pref.shimane.lg.jp/spch/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '岡山県立総合病院', 'prefecture': '岡山県', 'address': '岡山市北区伊福町2-6-1', 'phone': '086-252-6211', 'facility_type': 'hospital', 'beds': 450, 'website': 'https://www.okayama-pref-hospital.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '山口県立総合医療センター', 'prefecture': '山口県', 'address': '防府市大字大崎77-1', 'phone': '0835-22-4411', 'facility_type': 'hospital', 'beds': 574, 'website': 'https://www.ymghp.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '徳島県立中央病院', 'prefecture': '徳島県', 'address': '徳島市蔵本町1-10-3', 'phone': '088-631-7151', 'facility_type': 'hospital', 'beds': 504, 'website': 'https://www.tch.pref.tokushima.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '香川県立中央病院', 'prefecture': '香川県', 'address': '高松市番町5-4-16', 'phone': '087-811-3333', 'facility_type': 'hospital', 'beds': 500, 'website': 'https://www.kagawa-kenritsu-chuo.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '愛媛県立中央病院', 'prefecture': '愛媛県', 'address': '松山市春日町83', 'phone': '089-947-1111', 'facility_type': 'hospital', 'beds': 760, 'website': 'https://www.pref-ehime-chp.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '佐賀県医療センター好生館', 'prefecture': '佐賀県', 'address': '佐賀市嘉瀬町大字中原400', 'phone': '0952-24-2171', 'facility_type': 'hospital', 'beds': 660, 'website': 'https://www.kouseikan.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '長崎県立島原病院', 'prefecture': '長崎県', 'address': '島原市下川尻町7895', 'phone': '0957-63-1145', 'facility_type': 'hospital', 'beds': 350, 'website': 'https://www.pref.nagasaki.jp/shimabarahp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '熊本県立総合病院', 'prefecture': '熊本県', 'address': '八代市竹原町1-1-1', 'phone': '0965-32-3111', 'facility_type': 'hospital', 'beds': 500, 'website': 'https://www.kumamoto-pref-hp.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '大分県立病院', 'prefecture': '大分県', 'address': '大分市豊饒2-8-1', 'phone': '097-546-7111', 'facility_type': 'hospital', 'beds': 560, 'website': 'https://www.pref.oita.lg.jp/soshiki/10850/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '宮崎県立宮崎病院', 'prefecture': '宮崎県', 'address': '宮崎市北高松町5-30', 'phone': '0985-24-4181', 'facility_type': 'hospital', 'beds': 500, 'website': 'https://www.miyazaki-pref-hospital.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '沖縄県立中部病院', 'prefecture': '沖縄県', 'address': '沖縄市字仲宗根476', 'phone': '098-973-4111', 'facility_type': 'hospital', 'beds': 555, 'website': 'https://www.okinawa-chubuhp.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '沖縄県立南部医療センター・こども医療センター', 'prefecture': '沖縄県', 'address': '南風原町字新川118-1', 'phone': '098-888-0123', 'facility_type': 'hospital', 'beds': 543, 'website': 'https://www.nanbu-hosp.okinawa.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    # ── 市立病院 ───────────────────────────────────
    {'name': '旭川市立病院', 'prefecture': '北海道', 'address': '旭川市金星町1-1', 'phone': '0166-24-3181', 'facility_type': 'hospital', 'beds': 490, 'website': 'https://www.city.asahikawa.hokkaido.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '函館市立病院', 'prefecture': '北海道', 'address': '函館市港町1-10-1', 'phone': '0138-43-2000', 'facility_type': 'hospital', 'beds': 594, 'website': 'https://www.city.hakodate.hokkaido.jp/docs/2014011300062/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '仙台市立病院', 'prefecture': '宮城県', 'address': '仙台市青葉区寺町3-1', 'phone': '022-266-7111', 'facility_type': 'hospital', 'beds': 500, 'website': 'https://www.city.sendai.jp/shi-byoin/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '横浜市立市民病院', 'prefecture': '神奈川県', 'address': '横浜市保土ケ谷区岡沢町56', 'phone': '045-331-1961', 'facility_type': 'hospital', 'beds': 600, 'website': 'https://www.city.yokohama.lg.jp/shiminbyoin/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '川崎市立川崎病院', 'prefecture': '神奈川県', 'address': '川崎市川崎区川崎病院1', 'phone': '044-233-5521', 'facility_type': 'hospital', 'beds': 620, 'website': 'https://www.city.kawasaki.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '静岡市立静岡病院', 'prefecture': '静岡県', 'address': '静岡市葵区追手町10-93', 'phone': '054-253-3125', 'facility_type': 'hospital', 'beds': 546, 'website': 'https://www.shizuoka-city-hospital.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '浜松市立総合病院', 'prefecture': '静岡県', 'address': '浜松市中央区元城町111-1', 'phone': '053-454-0311', 'facility_type': 'hospital', 'beds': 780, 'website': 'https://www.hamamatsu-sougou.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '名古屋市立東部医療センター', 'prefecture': '愛知県', 'address': '名古屋市千種区若水1-2-23', 'phone': '052-721-7171', 'facility_type': 'hospital', 'beds': 586, 'website': 'https://www.higashi-iryocenter.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '京都市立病院', 'prefecture': '京都府', 'address': '京都市中京区五条御前通', 'phone': '075-311-5111', 'facility_type': 'hospital', 'beds': 650, 'website': 'https://www.kcgh.gr.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '神戸市立医療センター中央市民病院', 'prefecture': '兵庫県', 'address': '神戸市中央区港島南町2-1-1', 'phone': '078-302-4321', 'facility_type': 'hospital', 'beds': 780, 'website': 'https://www.kcho.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子'},
    {'name': '広島市立広島市民病院', 'prefecture': '広島県', 'address': '広島市中区基町7-33', 'phone': '082-221-2291', 'facility_type': 'hospital', 'beds': 700, 'website': 'https://www.hospital.city.hiroshima.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '北九州市立医療センター', 'prefecture': '福岡県', 'address': '北九州市小倉北区馬借1-3-1', 'phone': '093-541-1831', 'facility_type': 'hospital', 'beds': 560, 'website': 'https://www.kitakyushu-imc.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '那覇市立病院', 'prefecture': '沖縄県', 'address': '那覇市古島2-31-1', 'phone': '098-884-4131', 'facility_type': 'hospital', 'beds': 415, 'website': 'https://www.nahacity-hospital.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    # ── 済生会（追加）──────────────────────────────
    {'name': '済生会札幌病院', 'prefecture': '北海道', 'address': '札幌市中央区円山西町1-1-14', 'phone': '011-641-3131', 'facility_type': 'hospital', 'beds': 383, 'website': 'https://www.saiseikai-sapporo.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会新潟病院', 'prefecture': '新潟県', 'address': '新潟市西区寺地280-7', 'phone': '025-233-6161', 'facility_type': 'hospital', 'beds': 500, 'website': 'https://www.saiseikai-niigata.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会金沢病院', 'prefecture': '石川県', 'address': '金沢市寺町5-11-20', 'phone': '076-241-0210', 'facility_type': 'hospital', 'beds': 350, 'website': 'https://www.kanazawa.saiseikai.or.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会横浜市東部病院', 'prefecture': '神奈川県', 'address': '横浜市鶴見区下末吉3-6-1', 'phone': '045-576-3000', 'facility_type': 'hospital', 'beds': 780, 'website': 'https://www.saiseikai-yokohamashi-tobu.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会滋賀県病院', 'prefecture': '滋賀県', 'address': '栗東市小柿7-3-50', 'phone': '077-552-1221', 'facility_type': 'hospital', 'beds': 450, 'website': 'https://www.saiseikai-shiga.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会奈良病院', 'prefecture': '奈良県', 'address': '奈良市中登美ヶ丘8-1-1', 'phone': '0742-46-6001', 'facility_type': 'hospital', 'beds': 350, 'website': 'https://www.saiseikai-nara.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会和歌山病院', 'prefecture': '和歌山県', 'address': '和歌山市小松原通4-27', 'phone': '073-471-5550', 'facility_type': 'hospital', 'beds': 300, 'website': 'https://www.saiseikai-wakayama.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会松山病院', 'prefecture': '愛媛県', 'address': '松山市味酒町2-1-1', 'phone': '089-923-4058', 'facility_type': 'hospital', 'beds': 348, 'website': 'https://www.saiseikai-matsuyama.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会福岡病院', 'prefecture': '福岡県', 'address': '福岡市南区屋形原4-3-1', 'phone': '092-541-3231', 'facility_type': 'hospital', 'beds': 342, 'website': 'https://www.saiseikai-fukuoka.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '済生会熊本病院', 'prefecture': '熊本県', 'address': '熊本市南区近見5-3-1', 'phone': '096-351-8000', 'facility_type': 'hospital', 'beds': 500, 'website': 'https://www.saiseikai-kumamoto.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    # ── JA厚生連・徳洲会 ────────────────────────────
    {'name': '厚生連高岡病院', 'prefecture': '富山県', 'address': '高岡市永楽町5-10', 'phone': '0766-21-3930', 'facility_type': 'hospital', 'beds': 500, 'website': 'https://www.jaeat.or.jp/takaoka/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA長野厚生連佐久総合病院', 'prefecture': '長野県', 'address': '佐久市臼田197', 'phone': '0267-82-3131', 'facility_type': 'hospital', 'beds': 700, 'website': 'https://www.ja-nagano-koseiren.or.jp/saku/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': 'JA静岡厚生連遠州病院', 'prefecture': '静岡県', 'address': '浜松市中央区富塚町1088', 'phone': '053-474-2111', 'facility_type': 'hospital', 'beds': 421, 'website': 'https://www.enshukoseiren.or.jp/enshuhp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '徳洲会湘南鎌倉総合病院', 'prefecture': '神奈川県', 'address': '鎌倉市岡本1370-1', 'phone': '0467-46-1717', 'facility_type': 'hospital', 'beds': 440, 'website': 'https://www.shonan-kamakura.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '徳洲会千葉徳洲会病院', 'prefecture': '千葉県', 'address': '千葉市花見川区こてはし台5-1-1', 'phone': '043-257-0601', 'facility_type': 'hospital', 'beds': 330, 'website': 'https://chiba.tokushukai.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '岸和田徳洲会病院', 'prefecture': '大阪府', 'address': '岸和田市加守町4-27-1', 'phone': '072-445-9915', 'facility_type': 'hospital', 'beds': 400, 'website': 'https://kishiwada.tokushukai.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '湘南厚木病院', 'prefecture': '神奈川県', 'address': '厚木市関口1500', 'phone': '046-229-5111', 'facility_type': 'hospital', 'beds': 260, 'website': 'https://www.shonan-atsugi.or.jp/', 'departments': '内科,外科,小児科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    # ── 健診・クリニック系 ──────────────────────────
    {'name': '予防医学センター 東京本院', 'prefecture': '東京都', 'address': '東京都千代田区丸の内1-8-1', 'phone': '03-5220-1111', 'facility_type': 'health_center', 'departments': '', 'inspection_items': '血液,生化学,免疫,生理,一般検査'},
    {'name': '日本健康管理協会 大阪センター', 'prefecture': '大阪府', 'address': '大阪市北区梅田1-2-2', 'phone': '06-6343-6301', 'facility_type': 'health_center', 'departments': '', 'inspection_items': '血液,生化学,免疫,生理,一般検査'},
    {'name': 'PL病院', 'prefecture': '大阪府', 'address': '富田林市喜志町2-17-1', 'phone': '0721-24-3100', 'facility_type': 'hospital', 'beds': 650, 'website': 'https://www.pl-hospital.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '宝塚市立病院', 'prefecture': '兵庫県', 'address': '宝塚市小浜4-5-1', 'phone': '0797-87-1161', 'facility_type': 'hospital', 'beds': 432, 'website': 'https://www.takarazuka-city-hospital.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '西神戸医療センター', 'prefecture': '兵庫県', 'address': '神戸市西区糀台6-7-1', 'phone': '078-997-2200', 'facility_type': 'hospital', 'beds': 436, 'website': 'https://www.nishi-hp.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '姫路赤十字病院', 'prefecture': '兵庫県', 'address': '姫路市下手野1-12-1', 'phone': '079-294-2251', 'facility_type': 'hospital', 'beds': 606, 'website': 'https://www.himeji.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '奈良県立奈良病院', 'prefecture': '奈良県', 'address': '奈良市東紀寺町1-50-1', 'phone': '0742-24-1251', 'facility_type': 'hospital', 'beds': 400, 'website': 'https://www.pref.nara.jp/dd.aspx?menuid=3073', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '和歌山市立医科大学附属病院', 'prefecture': '和歌山県', 'address': '和歌山市小松原通4-13-4', 'phone': '073-422-6251', 'facility_type': 'hospital', 'beds': 350, 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '鳥取県立中央病院', 'prefecture': '鳥取県', 'address': '鳥取市江津730', 'phone': '0857-26-2271', 'facility_type': 'hospital', 'beds': 600, 'website': 'https://www.pref.tottori.lg.jp/dd.aspx?menuid=4616', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '山陰労災病院', 'prefecture': '鳥取県', 'address': '米子市皆生新田1-8-1', 'phone': '0859-33-8181', 'facility_type': 'hospital', 'beds': 400, 'website': 'https://www.sanin-rosai.or.jp/', 'departments': '内科,外科,小児科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '倉敷中央病院', 'prefecture': '岡山県', 'address': '倉敷市美和1-1-1', 'phone': '086-422-0210', 'facility_type': 'hospital', 'beds': 1178, 'website': 'https://www.kchnet.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理,遺伝子'},
    {'name': '広島赤十字・原爆病院', 'prefecture': '広島県', 'address': '広島市中区千田町1-9-6', 'phone': '082-241-3111', 'facility_type': 'hospital', 'beds': 516, 'website': 'https://www.hiroshima.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '下関市立市民病院', 'prefecture': '山口県', 'address': '下関市向洋町1-13-1', 'phone': '083-231-4111', 'facility_type': 'hospital', 'beds': 540, 'website': 'https://www.shimonoseki-chp.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '徳島赤十字病院', 'prefecture': '徳島県', 'address': '小松島市小松島町字井利ノ口103', 'phone': '0885-32-2555', 'facility_type': 'hospital', 'beds': 420, 'website': 'https://www.tokushima.jrc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '高知医療センター', 'prefecture': '高知県', 'address': '高知市池2125-1', 'phone': '088-837-3000', 'facility_type': 'hospital', 'beds': 744, 'website': 'https://www.khsc.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '大牟田市立病院', 'prefecture': '福岡県', 'address': '大牟田市大黒町2-10-1', 'phone': '0944-53-8282', 'facility_type': 'hospital', 'beds': 430, 'website': 'https://www.city.omuta.lg.jp/hospital/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '長崎市立病院機構 長崎みなとメディカルセンター', 'prefecture': '長崎県', 'address': '長崎市新地町6-39', 'phone': '095-822-3251', 'facility_type': 'hospital', 'beds': 560, 'website': 'https://www.nmhp.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    {'name': '宮崎市郡医師会病院', 'prefecture': '宮崎県', 'address': '宮崎市和知川原1-85', 'phone': '0985-77-9110', 'facility_type': 'hospital', 'beds': 423, 'website': 'https://www.miyazaki-ishikai.or.jp/', 'departments': '内科,外科,小児科,産婦人科,整形外科,眼科', 'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理'},
    # ── 公立病院 ───────────────────────────────────
    {
        'name': '東京都立墨東病院',
        'prefecture': '東京都',
        'address': '東京都墨田区江東橋4-23-15',
        'phone': '03-3633-6151',
        'facility_type': 'hospital',
        'beds': 765,
        'website': 'https://www.tmhp.jp/bokutoh/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科,救急科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理',
    },
    {
        'name': '大阪市立総合医療センター',
        'prefecture': '大阪府',
        'address': '大阪市都島区都島本通2-13-22',
        'phone': '06-6929-1221',
        'facility_type': 'hospital',
        'beds': 1064,
        'website': 'https://www.ommc.jp/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理',
    },
    {
        'name': '名古屋市立大学病院',
        'prefecture': '愛知県',
        'address': '名古屋市瑞穂区瑞穂町川澄1',
        'phone': '052-851-5511',
        'facility_type': 'hospital',
        'beds': 730,
        'website': 'https://hospital.med.nagoya-cu.ac.jp/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理',
    },
    {
        'name': '札幌市立病院',
        'prefecture': '北海道',
        'address': '札幌市中央区北11条西13丁目1-1',
        'phone': '011-726-2211',
        'facility_type': 'hospital',
        'beds': 724,
        'website': 'https://www.city.sapporo.jp/hospital/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理',
    },
    {
        'name': '福岡市立病院機構 福岡市民病院',
        'prefecture': '福岡県',
        'address': '福岡市博多区吉塚本町13-1',
        'phone': '092-692-3100',
        'facility_type': 'hospital',
        'beds': 620,
        'website': 'https://www.fch.or.jp/',
        'departments': '内科,外科,小児科,産婦人科,整形外科,眼科,耳鼻咽喉科',
        'inspection_items': '血液,生化学,免疫,微生物,病理,輸血,生理',
    },
]


class Command(BaseCommand):
    help = '主要病院・検査センターの初期データを登録する'

    def add_arguments(self, parser):
        parser.add_argument(
            '--force',
            action='store_true',
            help='既存データを上書き更新する',
        )

    def handle(self, *args, **options):
        force = options['force']
        created = updated = skipped = 0

        for data in HOSPITALS:
            existing = Hospital.objects.filter(
                name=data['name'],
                prefecture=data['prefecture'],
            ).first()

            if existing:
                if force:
                    for key, val in data.items():
                        setattr(existing, key, val)
                    existing.save()
                    updated += 1
                    self.stdout.write(f'  更新: {data["name"]}')
                else:
                    skipped += 1
                continue

            Hospital.objects.create(**data)
            created += 1
            self.stdout.write(f'  追加: {data["name"]}')

        self.stdout.write(self.style.SUCCESS(
            f'\n完了: 追加={created}件 / 更新={updated}件 / スキップ={skipped}件'
        ))
        if skipped and not force:
            self.stdout.write('  ※ 上書き更新するには --force オプションを付けてください')
