# Generated by Django 6.0.5 on 2026-05-19 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe顧客ID')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, verbose_name='StripeサブスクリプションID')),
                ('subscription_status', models.CharField(choices=[('inactive', '未契約'), ('active', '掲載中'), ('cancelled', 'キャンセル'), ('past_due', '支払い遅延')], default='inactive', max_length=20, verbose_name='サブスクリプション状態')),
                ('subscription_plan', models.CharField(blank=True, choices=[('monthly', '月額'), ('yearly', '年額')], max_length=10, verbose_name='プラン')),
                ('subscription_end', models.DateTimeField(blank=True, null=True, verbose_name='掲載期限')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_profiles', to='hospitals.hospital', verbose_name='担当病院')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '病院管理者プロフィール',
                'verbose_name_plural': '病院管理者プロフィール',
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='求人タイトル')),
                ('employment_type', models.CharField(choices=[('full_time', '常勤'), ('part_time', 'パート'), ('dispatch', '派遣'), ('contract', '契約社員')], max_length=15, verbose_name='雇用形態')),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='年収下限（万円）')),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='年収上限（万円）')),
                ('description', models.TextField(verbose_name='仕事内容')),
                ('requirements', models.TextField(blank=True, verbose_name='応募条件')),
                ('benefits', models.TextField(blank=True, verbose_name='福利厚生')),
                ('is_active', models.BooleanField(default=True, verbose_name='掲載中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_posts', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='hospitals.hospital', verbose_name='病院・施設')),
            ],
            options={
                'verbose_name': '求人情報',
                'verbose_name_plural': '求人情報',
                'ordering': ['-created_at'],
            },
        ),
    ]
