# Generated by Django 6.0.5 on 2026-05-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalAdminApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=200, verbose_name='施設名')),
                ('contact_name', models.CharField(max_length=100, verbose_name='担当者名')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('phone', models.CharField(max_length=20, verbose_name='電話番号')),
                ('message', models.TextField(blank=True, verbose_name='その他備考')),
                ('agreed_to_terms', models.BooleanField(default=False, verbose_name='利用規約同意')),
                ('status', models.CharField(choices=[('pending', '審査中'), ('approved', '承認済み'), ('rejected', '却下')], default='pending', max_length=10, verbose_name='審査状態')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='審査日時')),
            ],
            options={
                'verbose_name': '病院掲載申請',
                'verbose_name_plural': '病院掲載申請',
                'ordering': ['-created_at'],
            },
        ),
    ]
