# Generated by Django 6.0.5 on 2026-05-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_hospitaladminapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaladminapplication',
            name='official_url',
            field=models.URLField(blank=True, verbose_name='公式サイトURL'),
        ),
    ]
