# Generated by Django 6.0.5 on 2026-05-23 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_facilityrequest_average_age_and_more'),
        ('jobs', '0003_hospitaladminapplication_official_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaladminapplication',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_applications', to='hospitals.hospital', verbose_name='紐づけ病院'),
        ),
    ]
