# Generated by Django 6.0.5 on 2026-05-21 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='スラッグ')),
                ('category', models.CharField(choices=[('tips', '転職Tips'), ('knowledge', '業界知識'), ('facility', '施設紹介'), ('news', 'お知らせ'), ('other', 'その他')], default='tips', max_length=20, verbose_name='カテゴリ')),
                ('body', models.TextField(verbose_name='本文')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='サムネイル')),
                ('is_published', models.BooleanField(default=False, verbose_name='公開')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='公開日時')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='著者')),
            ],
            options={
                'verbose_name': '記事',
                'verbose_name_plural': '記事',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
