# Generated by Django 6.0.5 on 2026-05-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='お名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('category', models.CharField(blank=True, choices=[('general', '一般的なお問い合わせ'), ('review', 'レビューについて'), ('facility', '施設情報について'), ('account', 'アカウントについて'), ('other', 'その他')], max_length=20, verbose_name='種別')),
                ('message', models.TextField(verbose_name='内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='確認済み')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'お問い合わせ',
                'verbose_name_plural': 'お問い合わせ',
                'ordering': ['-created_at'],
            },
        ),
    ]
