# Generated by Django 6.0.5 on 2026-05-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日付')),
                ('ssh_blocked', models.IntegerField(default=0, verbose_name='SSH不正試行ブロック数')),
                ('nginx_errors', models.IntegerField(default=0, verbose_name='Nginxエラー数')),
                ('nginx_requests', models.IntegerField(default=0, verbose_name='総アクセス数')),
                ('disk_usage', models.CharField(blank=True, max_length=20, verbose_name='ディスク使用率')),
                ('memory_usage', models.CharField(blank=True, max_length=20, verbose_name='メモリ使用率')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'サーバーログ',
                'verbose_name_plural': 'サーバーログ',
                'ordering': ['-date'],
            },
        ),
    ]
