# Generated by Django 6.0.5 on 2026-05-19 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('annual_salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='年収（万円）')),
                ('overtime_hours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='月残業時間')),
                ('paid_leave_rate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='有給取得率（%）')),
                ('technician_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='技師の人数')),
                ('has_oncall', models.BooleanField(default=False, verbose_name='オンコールあり')),
                ('has_night_duty', models.BooleanField(default=False, verbose_name='当直あり')),
                ('has_night_shift', models.BooleanField(default=False, verbose_name='夜勤あり')),
                ('education_system', models.CharField(blank=True, choices=[('good', '充実している'), ('average', '普通'), ('poor', 'ほぼない')], max_length=10, verbose_name='教育体制')),
                ('equipment_age', models.CharField(blank=True, choices=[('new', '新しい'), ('average', '普通'), ('old', '古い')], max_length=10, verbose_name='機器の新しさ')),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', '常勤'), ('part_time', 'パート'), ('dispatch', '派遣')], max_length=15, verbose_name='雇用形態')),
                ('tenure_start_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='在籍開始年')),
                ('tenure_start_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='在籍開始月')),
                ('tenure_end_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='在籍終了年')),
                ('tenure_end_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='在籍終了月')),
                ('is_current', models.BooleanField(default=False, verbose_name='現在も在籍中')),
                ('overall_rating', models.PositiveSmallIntegerField(default=3, verbose_name='総合評価（1〜5）')),
                ('good_points', models.TextField(verbose_name='良かった点')),
                ('concerns', models.TextField(verbose_name='気になった点')),
                ('suitable_for', models.TextField(verbose_name='どんな人に向いている職場か')),
                ('agreed_to_terms', models.BooleanField(default=False, verbose_name='利用規約に同意')),
                ('status', models.CharField(choices=[('pending', '審査中'), ('approved', '公開'), ('rejected', '非公開'), ('objection', '確認中（異議申し立て）')], default='pending', max_length=20, verbose_name='公開状態')),
                ('ai_judgment', models.CharField(blank=True, choices=[('white', '問題なし'), ('gray', '要確認'), ('black', '非公開')], max_length=10, verbose_name='AI判定')),
                ('ai_reason', models.TextField(blank=True, verbose_name='AI判定理由')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='hospitals.hospital', verbose_name='病院・施設')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'verbose_name': 'レビュー',
                'verbose_name_plural': 'レビュー',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Objection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200, verbose_name='申立病院名')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='連絡先メール')),
                ('reason', models.TextField(verbose_name='申立理由')),
                ('status', models.CharField(choices=[('pending', '審査中'), ('waiting_reply', '投稿者返答待ち'), ('resolved_hide', '非公開処理済み'), ('resolved_keep', '公開維持')], default='pending', max_length=20, verbose_name='処理状態')),
                ('reply_deadline', models.DateTimeField(blank=True, null=True, verbose_name='返答期限')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objections', to='reviews.review', verbose_name='対象レビュー')),
            ],
            options={
                'verbose_name': '異議申し立て',
                'verbose_name_plural': '異議申し立て',
            },
        ),
    ]
