# Generated by Django 6.0.5 on 2026-05-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='education_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='教育体制評価（1〜5）'),
        ),
        migrations.AddField(
            model_name='review',
            name='equipment_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='設備・機器評価（1〜5）'),
        ),
        migrations.AddField(
            model_name='review',
            name='relationship_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='人間関係評価（1〜5）'),
        ),
        migrations.AddField(
            model_name='review',
            name='salary_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='給与評価（1〜5）'),
        ),
    ]
