# Generated by Django 6.0.5 on 2026-05-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_education_rating_review_equipment_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='average_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='平均年齢'),
        ),
        migrations.AddField(
            model_name='review',
            name='certification_support',
            field=models.CharField(blank=True, choices=[('good', '充実している'), ('sometimes', 'たまにある'), ('rarely', 'ほぼない')], max_length=10, verbose_name='認定資格のサポート'),
        ),
        migrations.AddField(
            model_name='review',
            name='gender_ratio',
            field=models.CharField(blank=True, max_length=50, verbose_name='技師の男女比'),
        ),
        migrations.AddField(
            model_name='review',
            name='has_blood_sampling',
            field=models.BooleanField(blank=True, null=True, verbose_name='採血行為あり'),
        ),
        migrations.AddField(
            model_name='review',
            name='joining_gap',
            field=models.TextField(blank=True, verbose_name='入職後のギャップ'),
        ),
        migrations.AddField(
            model_name='review',
            name='oncall_night_frequency',
            field=models.CharField(blank=True, choices=[('none', 'なし'), ('less_monthly', '月1回未満'), ('monthly_1_3', '月1〜3回'), ('weekly_1_2', '週1〜2回'), ('weekly_3_plus', '週3回以上')], max_length=15, verbose_name='オンコール・夜勤の頻度'),
        ),
        migrations.AddField(
            model_name='review',
            name='research_opportunity',
            field=models.CharField(blank=True, choices=[('good', '充実している'), ('sometimes', 'たまにある'), ('rarely', 'ほぼない')], max_length=10, verbose_name='学会発表・研究の機会'),
        ),
        migrations.AddField(
            model_name='review',
            name='work_style',
            field=models.CharField(blank=True, choices=[('specialized', '専門特化型（特定部署のみ）'), ('rotation', 'ローテーション型（全検査を幅広く）'), ('partial', '一部ローテーション（専門＋一部兼任）')], max_length=15, verbose_name='業務スタイル'),
        ),
    ]
