# Generated by Django 6.0.5 on 2026-05-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_average_age_review_certification_support_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='gender_ratio',
        ),
        migrations.AddField(
            model_name='review',
            name='male_ratio',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='男性技師の割合（0〜10）'),
        ),
    ]
