# Generated by Django 6.0.5 on 2026-05-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_reviewhelpful'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reject_reason',
            field=models.TextField(blank=True, verbose_name='却下理由（投稿者向け）'),
        ),
    ]
