# Generated by Django 6.0.5 on 2026-05-19 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='施設名')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='スラッグ')),
                ('prefecture', models.CharField(choices=[('北海道', '北海道'), ('青森県', '青森県'), ('岩手県', '岩手県'), ('宮城県', '宮城県'), ('秋田県', '秋田県'), ('山形県', '山形県'), ('福島県', '福島県'), ('茨城県', '茨城県'), ('栃木県', '栃木県'), ('群馬県', '群馬県'), ('埼玉県', '埼玉県'), ('千葉県', '千葉県'), ('東京都', '東京都'), ('神奈川県', '神奈川県'), ('新潟県', '新潟県'), ('富山県', '富山県'), ('石川県', '石川県'), ('福井県', '福井県'), ('山梨県', '山梨県'), ('長野県', '長野県'), ('岐阜県', '岐阜県'), ('静岡県', '静岡県'), ('愛知県', '愛知県'), ('三重県', '三重県'), ('滋賀県', '滋賀県'), ('京都府', '京都府'), ('大阪府', '大阪府'), ('兵庫県', '兵庫県'), ('奈良県', '奈良県'), ('和歌山県', '和歌山県'), ('鳥取県', '鳥取県'), ('島根県', '島根県'), ('岡山県', '岡山県'), ('広島県', '広島県'), ('山口県', '山口県'), ('徳島県', '徳島県'), ('香川県', '香川県'), ('愛媛県', '愛媛県'), ('高知県', '高知県'), ('福岡県', '福岡県'), ('佐賀県', '佐賀県'), ('長崎県', '長崎県'), ('熊本県', '熊本県'), ('大分県', '大分県'), ('宮崎県', '宮崎県'), ('鹿児島県', '鹿児島県'), ('沖縄県', '沖縄県')], max_length=10, verbose_name='都道府県')),
                ('address', models.CharField(max_length=300, verbose_name='住所')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('facility_type', models.CharField(choices=[('hospital', '病院'), ('clinic', 'クリニック・診療所'), ('lab', '検査センター'), ('other', 'その他')], default='hospital', max_length=20, verbose_name='施設種別')),
                ('beds', models.PositiveIntegerField(blank=True, null=True, verbose_name='病床数')),
                ('technician_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='技師数（概算）')),
                ('departments', models.TextField(blank=True, help_text='カンマ区切りで入力', verbose_name='診療科目')),
                ('inspection_items', models.TextField(blank=True, help_text='カンマ区切りで入力', verbose_name='検査項目')),
                ('website', models.URLField(blank=True, verbose_name='ウェブサイト')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '病院・施設',
                'verbose_name_plural': '病院・施設',
                'ordering': ['prefecture', 'name'],
            },
        ),
    ]
