# Generated by Django 6.0.5 on 2026-05-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='経度'),
        ),
    ]
