# Generated by Django 6.0.5 on 2026-05-20 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_hospital_lat_hospital_lng'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=200, verbose_name='施設名')),
                ('prefecture', models.CharField(choices=[('北海道', '北海道'), ('青森県', '青森県'), ('岩手県', '岩手県'), ('宮城県', '宮城県'), ('秋田県', '秋田県'), ('山形県', '山形県'), ('福島県', '福島県'), ('茨城県', '茨城県'), ('栃木県', '栃木県'), ('群馬県', '群馬県'), ('埼玉県', '埼玉県'), ('千葉県', '千葉県'), ('東京都', '東京都'), ('神奈川県', '神奈川県'), ('新潟県', '新潟県'), ('富山県', '富山県'), ('石川県', '石川県'), ('福井県', '福井県'), ('山梨県', '山梨県'), ('長野県', '長野県'), ('岐阜県', '岐阜県'), ('静岡県', '静岡県'), ('愛知県', '愛知県'), ('三重県', '三重県'), ('滋賀県', '滋賀県'), ('京都府', '京都府'), ('大阪府', '大阪府'), ('兵庫県', '兵庫県'), ('奈良県', '奈良県'), ('和歌山県', '和歌山県'), ('鳥取県', '鳥取県'), ('島根県', '島根県'), ('岡山県', '岡山県'), ('広島県', '広島県'), ('山口県', '山口県'), ('徳島県', '徳島県'), ('香川県', '香川県'), ('愛媛県', '愛媛県'), ('高知県', '高知県'), ('福岡県', '福岡県'), ('佐賀県', '佐賀県'), ('長崎県', '長崎県'), ('熊本県', '熊本県'), ('大分県', '大分県'), ('宮崎県', '宮崎県'), ('鹿児島県', '鹿児島県'), ('沖縄県', '沖縄県')], max_length=10, verbose_name='都道府県')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='住所')),
                ('facility_type', models.CharField(choices=[('hospital', '病院'), ('clinic', 'クリニック・診療所'), ('lab', '検査センター'), ('other', 'その他')], default='hospital', max_length=20, verbose_name='施設種別')),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='総合評価')),
                ('annual_salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='年収（万円）')),
                ('overtime_hours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='月残業時間')),
                ('employment_type', models.CharField(blank=True, max_length=15, verbose_name='雇用形態')),
                ('has_oncall', models.BooleanField(default=False, verbose_name='オンコールあり')),
                ('has_night_duty', models.BooleanField(default=False, verbose_name='当直あり')),
                ('has_night_shift', models.BooleanField(default=False, verbose_name='夜勤あり')),
                ('good_points', models.TextField(blank=True, verbose_name='良かった点')),
                ('concerns', models.TextField(blank=True, verbose_name='気になった点')),
                ('suitable_for', models.TextField(blank=True, verbose_name='向いている人')),
                ('joining_gap', models.TextField(blank=True, verbose_name='入職後のギャップ')),
                ('status', models.CharField(choices=[('pending', '審査待ち'), ('needs_review', '要確認'), ('approved', '承認済み'), ('rejected', '却下')], default='pending', max_length=15, verbose_name='ステータス')),
                ('admin_note', models.TextField(blank=True, verbose_name='管理者メモ・質問')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_requests', to=settings.AUTH_USER_MODEL, verbose_name='申請者')),
            ],
            options={
                'verbose_name': '施設登録申請',
                'verbose_name_plural': '施設登録申請',
                'ordering': ['-created_at'],
            },
        ),
    ]
