# Generated by Django 6.0.5 on 2026-05-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_facilityrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityrequest',
            name='average_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='平均年齢'),
        ),
        migrations.AddField(
            model_name='facilityrequest',
            name='certification_support',
            field=models.CharField(blank=True, max_length=10, verbose_name='資格サポート'),
        ),
        migrations.AddField(
            model_name='facilityrequest',
            name='education_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='教育体制評価'),
        ),
        migrations.AddField(
            model_name='facilityrequest',
            name='education_system',
            field=models.CharField(blank=True, max_length=10, verbose_name='教育体制'),
        ),
        migrations.AddField(
            model_name='facilityrequest',
            name='equipment_age',
            field=models.CharField(blank=True, max_length=10, verbose_name='機器の新しさ'),
        ),
        migrations.AddField(
            model_name='facilityrequest',
            name='equipment_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='設備評価'),
        ),
        migrations.AddField(
            model_name='facilityrequest',
            name='has_blood_sampling',
            field=models.BooleanField(blank=True, null=True, verbose_name='採血行為あり'),
        ),
        migrations.AddField(
            model_name='facilityrequest',
            name='male_ratio',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='男性技師の割合（0〜10）'),
        ),
        migrations.AddField(
            model_name='facilityrequest',
            name='oncall_night_frequency',
            field=models.CharField(blank=True, max_length=15, verbose_name='オンコール・夜勤の頻度'),
        ),
        migrations.AddField(
            model_name='facilityrequest',
            name='paid_leave_rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='有給取得率（%）'),
        ),
        migrations.AddField(
            model_name='facilityrequest',
            name='relationship_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='人間関係評価'),
        ),
        migrations.AddField(
            model_name='facilityrequest',
            name='research_opportunity',
            field=models.CharField(blank=True, max_length=10, verbose_name='学会・研究の機会'),
        ),
        migrations.AddField(
            model_name='facilityrequest',
            name='salary_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='給与評価'),
        ),
        migrations.AddField(
            model_name='facilityrequest',
            name='technician_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='技師の人数'),
        ),
        migrations.AddField(
            model_name='facilityrequest',
            name='work_style',
            field=models.CharField(blank=True, max_length=15, verbose_name='業務スタイル'),
        ),
    ]
